// Code generated by ent, DO NOT EDIT.

package adaptermodelbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// AdapterID applies equality check predicate on the "adapter_id" field. It's identical to AdapterIDEQ.
func AdapterID(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldAdapterID, v))
}

// SourceModelID applies equality check predicate on the "source_model_id" field. It's identical to SourceModelIDEQ.
func SourceModelID(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldSourceModelID, v))
}

// ModelGroupID applies equality check predicate on the "model_group_id" field. It's identical to ModelGroupIDEQ.
func ModelGroupID(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldModelGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldEnabled, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLTE(FieldDeletedAt, v))
}

// AdapterIDEQ applies the EQ predicate on the "adapter_id" field.
func AdapterIDEQ(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldAdapterID, v))
}

// AdapterIDNEQ applies the NEQ predicate on the "adapter_id" field.
func AdapterIDNEQ(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldAdapterID, v))
}

// AdapterIDIn applies the In predicate on the "adapter_id" field.
func AdapterIDIn(vs ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldAdapterID, vs...))
}

// AdapterIDNotIn applies the NotIn predicate on the "adapter_id" field.
func AdapterIDNotIn(vs ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldAdapterID, vs...))
}

// SourceModelIDEQ applies the EQ predicate on the "source_model_id" field.
func SourceModelIDEQ(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldSourceModelID, v))
}

// SourceModelIDNEQ applies the NEQ predicate on the "source_model_id" field.
func SourceModelIDNEQ(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldSourceModelID, v))
}

// SourceModelIDIn applies the In predicate on the "source_model_id" field.
func SourceModelIDIn(vs ...string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldSourceModelID, vs...))
}

// SourceModelIDNotIn applies the NotIn predicate on the "source_model_id" field.
func SourceModelIDNotIn(vs ...string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldSourceModelID, vs...))
}

// SourceModelIDGT applies the GT predicate on the "source_model_id" field.
func SourceModelIDGT(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGT(FieldSourceModelID, v))
}

// SourceModelIDGTE applies the GTE predicate on the "source_model_id" field.
func SourceModelIDGTE(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGTE(FieldSourceModelID, v))
}

// SourceModelIDLT applies the LT predicate on the "source_model_id" field.
func SourceModelIDLT(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLT(FieldSourceModelID, v))
}

// SourceModelIDLTE applies the LTE predicate on the "source_model_id" field.
func SourceModelIDLTE(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLTE(FieldSourceModelID, v))
}

// SourceModelIDContains applies the Contains predicate on the "source_model_id" field.
func SourceModelIDContains(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldContains(FieldSourceModelID, v))
}

// SourceModelIDHasPrefix applies the HasPrefix predicate on the "source_model_id" field.
func SourceModelIDHasPrefix(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldHasPrefix(FieldSourceModelID, v))
}

// SourceModelIDHasSuffix applies the HasSuffix predicate on the "source_model_id" field.
func SourceModelIDHasSuffix(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldHasSuffix(FieldSourceModelID, v))
}

// SourceModelIDEqualFold applies the EqualFold predicate on the "source_model_id" field.
func SourceModelIDEqualFold(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEqualFold(FieldSourceModelID, v))
}

// SourceModelIDContainsFold applies the ContainsFold predicate on the "source_model_id" field.
func SourceModelIDContainsFold(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldContainsFold(FieldSourceModelID, v))
}

// ModelGroupIDEQ applies the EQ predicate on the "model_group_id" field.
func ModelGroupIDEQ(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldModelGroupID, v))
}

// ModelGroupIDNEQ applies the NEQ predicate on the "model_group_id" field.
func ModelGroupIDNEQ(v int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldModelGroupID, v))
}

// ModelGroupIDIn applies the In predicate on the "model_group_id" field.
func ModelGroupIDIn(vs ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldModelGroupID, vs...))
}

// ModelGroupIDNotIn applies the NotIn predicate on the "model_group_id" field.
func ModelGroupIDNotIn(vs ...int) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldModelGroupID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldEnabled, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.FieldContainsFold(FieldRemark, v))
}

// HasAdapter applies the HasEdge predicate on the "adapter" edge.
func HasAdapter() predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AdapterTable, AdapterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdapterWith applies the HasEdge predicate on the "adapter" edge with a given conditions (other predicates).
func HasAdapterWith(preds ...predicate.Adapter) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(func(s *sql.Selector) {
		step := newAdapterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasModelGroup applies the HasEdge predicate on the "model_group" edge.
func HasModelGroup() predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ModelGroupTable, ModelGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelGroupWith applies the HasEdge predicate on the "model_group" edge with a given conditions (other predicates).
func HasModelGroupWith(preds ...predicate.ModelGroup) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(func(s *sql.Selector) {
		step := newModelGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdapterModelBinding) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdapterModelBinding) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdapterModelBinding) predicate.AdapterModelBinding {
	return predicate.AdapterModelBinding(sql.NotPredicates(p))
}
