// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/adaptermodelbinding"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// AdapterModelBindingDelete is the builder for deleting a AdapterModelBinding entity.
type AdapterModelBindingDelete struct {
	config
	hooks    []Hook
	mutation *AdapterModelBindingMutation
}

// Where appends a list predicates to the AdapterModelBindingDelete builder.
func (_d *AdapterModelBindingDelete) Where(ps ...predicate.AdapterModelBinding) *AdapterModelBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdapterModelBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdapterModelBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdapterModelBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adaptermodelbinding.Table, sqlgraph.NewFieldSpec(adaptermodelbinding.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdapterModelBindingDeleteOne is the builder for deleting a single AdapterModelBinding entity.
type AdapterModelBindingDeleteOne struct {
	_d *AdapterModelBindingDelete
}

// Where appends a list predicates to the AdapterModelBindingDelete builder.
func (_d *AdapterModelBindingDeleteOne) Where(ps ...predicate.AdapterModelBinding) *AdapterModelBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdapterModelBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adaptermodelbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdapterModelBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
