// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/adapter"
	"github.com/mutallipp/llm-proxy/internal/ent/adaptermodelbinding"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroup"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// AdapterModelBindingQuery is the builder for querying AdapterModelBinding entities.
type AdapterModelBindingQuery struct {
	config
	ctx            *QueryContext
	order          []adaptermodelbinding.OrderOption
	inters         []Interceptor
	predicates     []predicate.AdapterModelBinding
	withAdapter    *AdapterQuery
	withModelGroup *ModelGroupQuery
	loadTotal      []func(context.Context, []*AdapterModelBinding) error
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdapterModelBindingQuery builder.
func (_q *AdapterModelBindingQuery) Where(ps ...predicate.AdapterModelBinding) *AdapterModelBindingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AdapterModelBindingQuery) Limit(limit int) *AdapterModelBindingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AdapterModelBindingQuery) Offset(offset int) *AdapterModelBindingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AdapterModelBindingQuery) Unique(unique bool) *AdapterModelBindingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AdapterModelBindingQuery) Order(o ...adaptermodelbinding.OrderOption) *AdapterModelBindingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAdapter chains the current query on the "adapter" edge.
func (_q *AdapterModelBindingQuery) QueryAdapter() *AdapterQuery {
	query := (&AdapterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adaptermodelbinding.Table, adaptermodelbinding.FieldID, selector),
			sqlgraph.To(adapter.Table, adapter.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adaptermodelbinding.AdapterTable, adaptermodelbinding.AdapterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModelGroup chains the current query on the "model_group" edge.
func (_q *AdapterModelBindingQuery) QueryModelGroup() *ModelGroupQuery {
	query := (&ModelGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adaptermodelbinding.Table, adaptermodelbinding.FieldID, selector),
			sqlgraph.To(modelgroup.Table, modelgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adaptermodelbinding.ModelGroupTable, adaptermodelbinding.ModelGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdapterModelBinding entity from the query.
// Returns a *NotFoundError when no AdapterModelBinding was found.
func (_q *AdapterModelBindingQuery) First(ctx context.Context) (*AdapterModelBinding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adaptermodelbinding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) FirstX(ctx context.Context) *AdapterModelBinding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdapterModelBinding ID from the query.
// Returns a *NotFoundError when no AdapterModelBinding ID was found.
func (_q *AdapterModelBindingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adaptermodelbinding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdapterModelBinding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdapterModelBinding entity is found.
// Returns a *NotFoundError when no AdapterModelBinding entities are found.
func (_q *AdapterModelBindingQuery) Only(ctx context.Context) (*AdapterModelBinding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adaptermodelbinding.Label}
	default:
		return nil, &NotSingularError{adaptermodelbinding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) OnlyX(ctx context.Context) *AdapterModelBinding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdapterModelBinding ID in the query.
// Returns a *NotSingularError when more than one AdapterModelBinding ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AdapterModelBindingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adaptermodelbinding.Label}
	default:
		err = &NotSingularError{adaptermodelbinding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdapterModelBindings.
func (_q *AdapterModelBindingQuery) All(ctx context.Context) ([]*AdapterModelBinding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdapterModelBinding, *AdapterModelBindingQuery]()
	return withInterceptors[[]*AdapterModelBinding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) AllX(ctx context.Context) []*AdapterModelBinding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdapterModelBinding IDs.
func (_q *AdapterModelBindingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(adaptermodelbinding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AdapterModelBindingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AdapterModelBindingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AdapterModelBindingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AdapterModelBindingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdapterModelBindingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AdapterModelBindingQuery) Clone() *AdapterModelBindingQuery {
	if _q == nil {
		return nil
	}
	return &AdapterModelBindingQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]adaptermodelbinding.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.AdapterModelBinding{}, _q.predicates...),
		withAdapter:    _q.withAdapter.Clone(),
		withModelGroup: _q.withModelGroup.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAdapter tells the query-builder to eager-load the nodes that are connected to
// the "adapter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdapterModelBindingQuery) WithAdapter(opts ...func(*AdapterQuery)) *AdapterModelBindingQuery {
	query := (&AdapterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdapter = query
	return _q
}

// WithModelGroup tells the query-builder to eager-load the nodes that are connected to
// the "model_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdapterModelBindingQuery) WithModelGroup(opts ...func(*ModelGroupQuery)) *AdapterModelBindingQuery {
	query := (&ModelGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModelGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdapterModelBinding.Query().
//		GroupBy(adaptermodelbinding.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AdapterModelBindingQuery) GroupBy(field string, fields ...string) *AdapterModelBindingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdapterModelBindingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = adaptermodelbinding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AdapterModelBinding.Query().
//		Select(adaptermodelbinding.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AdapterModelBindingQuery) Select(fields ...string) *AdapterModelBindingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AdapterModelBindingSelect{AdapterModelBindingQuery: _q}
	sbuild.label = adaptermodelbinding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdapterModelBindingSelect configured with the given aggregations.
func (_q *AdapterModelBindingQuery) Aggregate(fns ...AggregateFunc) *AdapterModelBindingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AdapterModelBindingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !adaptermodelbinding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AdapterModelBindingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdapterModelBinding, error) {
	var (
		nodes       = []*AdapterModelBinding{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAdapter != nil,
			_q.withModelGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdapterModelBinding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdapterModelBinding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAdapter; query != nil {
		if err := _q.loadAdapter(ctx, query, nodes, nil,
			func(n *AdapterModelBinding, e *Adapter) { n.Edges.Adapter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withModelGroup; query != nil {
		if err := _q.loadModelGroup(ctx, query, nodes, nil,
			func(n *AdapterModelBinding, e *ModelGroup) { n.Edges.ModelGroup = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AdapterModelBindingQuery) loadAdapter(ctx context.Context, query *AdapterQuery, nodes []*AdapterModelBinding, init func(*AdapterModelBinding), assign func(*AdapterModelBinding, *Adapter)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AdapterModelBinding)
	for i := range nodes {
		fk := nodes[i].AdapterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adapter.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "adapter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdapterModelBindingQuery) loadModelGroup(ctx context.Context, query *ModelGroupQuery, nodes []*AdapterModelBinding, init func(*AdapterModelBinding), assign func(*AdapterModelBinding, *ModelGroup)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AdapterModelBinding)
	for i := range nodes {
		fk := nodes[i].ModelGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(modelgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AdapterModelBindingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AdapterModelBindingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adaptermodelbinding.Table, adaptermodelbinding.Columns, sqlgraph.NewFieldSpec(adaptermodelbinding.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adaptermodelbinding.FieldID)
		for i := range fields {
			if fields[i] != adaptermodelbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAdapter != nil {
			_spec.Node.AddColumnOnce(adaptermodelbinding.FieldAdapterID)
		}
		if _q.withModelGroup != nil {
			_spec.Node.AddColumnOnce(adaptermodelbinding.FieldModelGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AdapterModelBindingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(adaptermodelbinding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = adaptermodelbinding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AdapterModelBindingQuery) Modify(modifiers ...func(s *sql.Selector)) *AdapterModelBindingSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AdapterModelBindingGroupBy is the group-by builder for AdapterModelBinding entities.
type AdapterModelBindingGroupBy struct {
	selector
	build *AdapterModelBindingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AdapterModelBindingGroupBy) Aggregate(fns ...AggregateFunc) *AdapterModelBindingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AdapterModelBindingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdapterModelBindingQuery, *AdapterModelBindingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AdapterModelBindingGroupBy) sqlScan(ctx context.Context, root *AdapterModelBindingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdapterModelBindingSelect is the builder for selecting fields of AdapterModelBinding entities.
type AdapterModelBindingSelect struct {
	*AdapterModelBindingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AdapterModelBindingSelect) Aggregate(fns ...AggregateFunc) *AdapterModelBindingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AdapterModelBindingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdapterModelBindingQuery, *AdapterModelBindingSelect](ctx, _s.AdapterModelBindingQuery, _s, _s.inters, v)
}

func (_s *AdapterModelBindingSelect) sqlScan(ctx context.Context, root *AdapterModelBindingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AdapterModelBindingSelect) Modify(modifiers ...func(s *sql.Selector)) *AdapterModelBindingSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
