// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/adapter"
	"github.com/mutallipp/llm-proxy/internal/ent/adaptermodelbinding"
	"github.com/mutallipp/llm-proxy/internal/ent/model"
)

// AdapterModelBindingCreate is the builder for creating a AdapterModelBinding entity.
type AdapterModelBindingCreate struct {
	config
	mutation *AdapterModelBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdapterModelBindingCreate) SetCreatedAt(v time.Time) *AdapterModelBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdapterModelBindingCreate) SetNillableCreatedAt(v *time.Time) *AdapterModelBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdapterModelBindingCreate) SetUpdatedAt(v time.Time) *AdapterModelBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdapterModelBindingCreate) SetNillableUpdatedAt(v *time.Time) *AdapterModelBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AdapterModelBindingCreate) SetDeletedAt(v int) *AdapterModelBindingCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AdapterModelBindingCreate) SetNillableDeletedAt(v *int) *AdapterModelBindingCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetAdapterID sets the "adapter_id" field.
func (_c *AdapterModelBindingCreate) SetAdapterID(v int) *AdapterModelBindingCreate {
	_c.mutation.SetAdapterID(v)
	return _c
}

// SetSourceModelID sets the "source_model_id" field.
func (_c *AdapterModelBindingCreate) SetSourceModelID(v string) *AdapterModelBindingCreate {
	_c.mutation.SetSourceModelID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *AdapterModelBindingCreate) SetModelID(v int) *AdapterModelBindingCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AdapterModelBindingCreate) SetEnabled(v bool) *AdapterModelBindingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AdapterModelBindingCreate) SetNillableEnabled(v *bool) *AdapterModelBindingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *AdapterModelBindingCreate) SetRemark(v string) *AdapterModelBindingCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *AdapterModelBindingCreate) SetNillableRemark(v *string) *AdapterModelBindingCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetAdapter sets the "adapter" edge to the Adapter entity.
func (_c *AdapterModelBindingCreate) SetAdapter(v *Adapter) *AdapterModelBindingCreate {
	return _c.SetAdapterID(v.ID)
}

// SetModel sets the "model" edge to the Model entity.
func (_c *AdapterModelBindingCreate) SetModel(v *Model) *AdapterModelBindingCreate {
	return _c.SetModelID(v.ID)
}

// Mutation returns the AdapterModelBindingMutation object of the builder.
func (_c *AdapterModelBindingCreate) Mutation() *AdapterModelBindingMutation {
	return _c.mutation
}

// Save creates the AdapterModelBinding in the database.
func (_c *AdapterModelBindingCreate) Save(ctx context.Context) (*AdapterModelBinding, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdapterModelBindingCreate) SaveX(ctx context.Context) *AdapterModelBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterModelBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterModelBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdapterModelBindingCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if adaptermodelbinding.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized adaptermodelbinding.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := adaptermodelbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if adaptermodelbinding.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adaptermodelbinding.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adaptermodelbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := adaptermodelbinding.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := adaptermodelbinding.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdapterModelBindingCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "AdapterModelBinding.deleted_at"`)}
	}
	if _, ok := _c.mutation.AdapterID(); !ok {
		return &ValidationError{Name: "adapter_id", err: errors.New(`ent: missing required field "AdapterModelBinding.adapter_id"`)}
	}
	if _, ok := _c.mutation.SourceModelID(); !ok {
		return &ValidationError{Name: "source_model_id", err: errors.New(`ent: missing required field "AdapterModelBinding.source_model_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "AdapterModelBinding.model_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AdapterModelBinding.enabled"`)}
	}
	if len(_c.mutation.AdapterIDs()) == 0 {
		return &ValidationError{Name: "adapter", err: errors.New(`ent: missing required edge "AdapterModelBinding.adapter"`)}
	}
	if len(_c.mutation.ModelIDs()) == 0 {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required edge "AdapterModelBinding.model"`)}
	}
	return nil
}

func (_c *AdapterModelBindingCreate) sqlSave(ctx context.Context) (*AdapterModelBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdapterModelBindingCreate) createSpec() (*AdapterModelBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &AdapterModelBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adaptermodelbinding.Table, sqlgraph.NewFieldSpec(adaptermodelbinding.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adaptermodelbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adaptermodelbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(adaptermodelbinding.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.SourceModelID(); ok {
		_spec.SetField(adaptermodelbinding.FieldSourceModelID, field.TypeString, value)
		_node.SourceModelID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(adaptermodelbinding.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(adaptermodelbinding.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if nodes := _c.mutation.AdapterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adaptermodelbinding.AdapterTable,
			Columns: []string{adaptermodelbinding.AdapterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdapterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adaptermodelbinding.ModelTable,
			Columns: []string{adaptermodelbinding.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdapterModelBinding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterModelBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterModelBindingCreate) OnConflict(opts ...sql.ConflictOption) *AdapterModelBindingUpsertOne {
	_c.conflict = opts
	return &AdapterModelBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdapterModelBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterModelBindingCreate) OnConflictColumns(columns ...string) *AdapterModelBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterModelBindingUpsertOne{
		create: _c,
	}
}

type (
	// AdapterModelBindingUpsertOne is the builder for "upsert"-ing
	//  one AdapterModelBinding node.
	AdapterModelBindingUpsertOne struct {
		create *AdapterModelBindingCreate
	}

	// AdapterModelBindingUpsert is the "OnConflict" setter.
	AdapterModelBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AdapterModelBindingUpsert) SetUpdatedAt(v time.Time) *AdapterModelBindingUpsert {
	u.Set(adaptermodelbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdapterModelBindingUpsert) UpdateUpdatedAt() *AdapterModelBindingUpsert {
	u.SetExcluded(adaptermodelbinding.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdapterModelBindingUpsert) SetDeletedAt(v int) *AdapterModelBindingUpsert {
	u.Set(adaptermodelbinding.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdapterModelBindingUpsert) UpdateDeletedAt() *AdapterModelBindingUpsert {
	u.SetExcluded(adaptermodelbinding.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AdapterModelBindingUpsert) AddDeletedAt(v int) *AdapterModelBindingUpsert {
	u.Add(adaptermodelbinding.FieldDeletedAt, v)
	return u
}

// SetSourceModelID sets the "source_model_id" field.
func (u *AdapterModelBindingUpsert) SetSourceModelID(v string) *AdapterModelBindingUpsert {
	u.Set(adaptermodelbinding.FieldSourceModelID, v)
	return u
}

// UpdateSourceModelID sets the "source_model_id" field to the value that was provided on create.
func (u *AdapterModelBindingUpsert) UpdateSourceModelID() *AdapterModelBindingUpsert {
	u.SetExcluded(adaptermodelbinding.FieldSourceModelID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AdapterModelBindingUpsert) SetEnabled(v bool) *AdapterModelBindingUpsert {
	u.Set(adaptermodelbinding.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdapterModelBindingUpsert) UpdateEnabled() *AdapterModelBindingUpsert {
	u.SetExcluded(adaptermodelbinding.FieldEnabled)
	return u
}

// SetRemark sets the "remark" field.
func (u *AdapterModelBindingUpsert) SetRemark(v string) *AdapterModelBindingUpsert {
	u.Set(adaptermodelbinding.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AdapterModelBindingUpsert) UpdateRemark() *AdapterModelBindingUpsert {
	u.SetExcluded(adaptermodelbinding.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *AdapterModelBindingUpsert) ClearRemark() *AdapterModelBindingUpsert {
	u.SetNull(adaptermodelbinding.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdapterModelBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterModelBindingUpsertOne) UpdateNewValues() *AdapterModelBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adaptermodelbinding.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.AdapterID(); exists {
			s.SetIgnore(adaptermodelbinding.FieldAdapterID)
		}
		if _, exists := u.create.mutation.ModelID(); exists {
			s.SetIgnore(adaptermodelbinding.FieldModelID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdapterModelBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdapterModelBindingUpsertOne) Ignore() *AdapterModelBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterModelBindingUpsertOne) DoNothing() *AdapterModelBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterModelBindingCreate.OnConflict
// documentation for more info.
func (u *AdapterModelBindingUpsertOne) Update(set func(*AdapterModelBindingUpsert)) *AdapterModelBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterModelBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdapterModelBindingUpsertOne) SetUpdatedAt(v time.Time) *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertOne) UpdateUpdatedAt() *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdapterModelBindingUpsertOne) SetDeletedAt(v int) *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AdapterModelBindingUpsertOne) AddDeletedAt(v int) *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertOne) UpdateDeletedAt() *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetSourceModelID sets the "source_model_id" field.
func (u *AdapterModelBindingUpsertOne) SetSourceModelID(v string) *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetSourceModelID(v)
	})
}

// UpdateSourceModelID sets the "source_model_id" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertOne) UpdateSourceModelID() *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateSourceModelID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AdapterModelBindingUpsertOne) SetEnabled(v bool) *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertOne) UpdateEnabled() *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *AdapterModelBindingUpsertOne) SetRemark(v string) *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertOne) UpdateRemark() *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *AdapterModelBindingUpsertOne) ClearRemark() *AdapterModelBindingUpsertOne {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *AdapterModelBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterModelBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterModelBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdapterModelBindingUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdapterModelBindingUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdapterModelBindingCreateBulk is the builder for creating many AdapterModelBinding entities in bulk.
type AdapterModelBindingCreateBulk struct {
	config
	err      error
	builders []*AdapterModelBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the AdapterModelBinding entities in the database.
func (_c *AdapterModelBindingCreateBulk) Save(ctx context.Context) ([]*AdapterModelBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdapterModelBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdapterModelBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdapterModelBindingCreateBulk) SaveX(ctx context.Context) []*AdapterModelBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterModelBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterModelBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdapterModelBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterModelBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterModelBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdapterModelBindingUpsertBulk {
	_c.conflict = opts
	return &AdapterModelBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdapterModelBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterModelBindingCreateBulk) OnConflictColumns(columns ...string) *AdapterModelBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterModelBindingUpsertBulk{
		create: _c,
	}
}

// AdapterModelBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of AdapterModelBinding nodes.
type AdapterModelBindingUpsertBulk struct {
	create *AdapterModelBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdapterModelBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterModelBindingUpsertBulk) UpdateNewValues() *AdapterModelBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adaptermodelbinding.FieldCreatedAt)
			}
			if _, exists := b.mutation.AdapterID(); exists {
				s.SetIgnore(adaptermodelbinding.FieldAdapterID)
			}
			if _, exists := b.mutation.ModelID(); exists {
				s.SetIgnore(adaptermodelbinding.FieldModelID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdapterModelBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdapterModelBindingUpsertBulk) Ignore() *AdapterModelBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterModelBindingUpsertBulk) DoNothing() *AdapterModelBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterModelBindingCreateBulk.OnConflict
// documentation for more info.
func (u *AdapterModelBindingUpsertBulk) Update(set func(*AdapterModelBindingUpsert)) *AdapterModelBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterModelBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdapterModelBindingUpsertBulk) SetUpdatedAt(v time.Time) *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertBulk) UpdateUpdatedAt() *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdapterModelBindingUpsertBulk) SetDeletedAt(v int) *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AdapterModelBindingUpsertBulk) AddDeletedAt(v int) *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertBulk) UpdateDeletedAt() *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetSourceModelID sets the "source_model_id" field.
func (u *AdapterModelBindingUpsertBulk) SetSourceModelID(v string) *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetSourceModelID(v)
	})
}

// UpdateSourceModelID sets the "source_model_id" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertBulk) UpdateSourceModelID() *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateSourceModelID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AdapterModelBindingUpsertBulk) SetEnabled(v bool) *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertBulk) UpdateEnabled() *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *AdapterModelBindingUpsertBulk) SetRemark(v string) *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AdapterModelBindingUpsertBulk) UpdateRemark() *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *AdapterModelBindingUpsertBulk) ClearRemark() *AdapterModelBindingUpsertBulk {
	return u.Update(func(s *AdapterModelBindingUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *AdapterModelBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdapterModelBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterModelBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterModelBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
