// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/adapter"
	"github.com/looplj/axonhub/internal/ent/adaptermodelbinding"
	"github.com/looplj/axonhub/internal/ent/modelgroup"
)

// AdapterModelBinding is the model entity for the AdapterModelBinding schema.
type AdapterModelBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// AdapterID holds the value of the "adapter_id" field.
	AdapterID int `json:"adapter_id,omitempty"`
	// SourceModelID holds the value of the "source_model_id" field.
	SourceModelID string `json:"source_model_id,omitempty"`
	// ModelGroupID holds the value of the "model_group_id" field.
	ModelGroupID int `json:"model_group_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdapterModelBindingQuery when eager-loading is set.
	Edges        AdapterModelBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdapterModelBindingEdges holds the relations/edges for other nodes in the graph.
type AdapterModelBindingEdges struct {
	// Adapter holds the value of the adapter edge.
	Adapter *Adapter `json:"adapter,omitempty"`
	// ModelGroup holds the value of the model_group edge.
	ModelGroup *ModelGroup `json:"model_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AdapterOrErr returns the Adapter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdapterModelBindingEdges) AdapterOrErr() (*Adapter, error) {
	if e.Adapter != nil {
		return e.Adapter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: adapter.Label}
	}
	return nil, &NotLoadedError{edge: "adapter"}
}

// ModelGroupOrErr returns the ModelGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdapterModelBindingEdges) ModelGroupOrErr() (*ModelGroup, error) {
	if e.ModelGroup != nil {
		return e.ModelGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: modelgroup.Label}
	}
	return nil, &NotLoadedError{edge: "model_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdapterModelBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adaptermodelbinding.FieldEnabled:
			values[i] = new(sql.NullBool)
		case adaptermodelbinding.FieldID, adaptermodelbinding.FieldDeletedAt, adaptermodelbinding.FieldAdapterID, adaptermodelbinding.FieldModelGroupID:
			values[i] = new(sql.NullInt64)
		case adaptermodelbinding.FieldSourceModelID, adaptermodelbinding.FieldRemark:
			values[i] = new(sql.NullString)
		case adaptermodelbinding.FieldCreatedAt, adaptermodelbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdapterModelBinding fields.
func (_m *AdapterModelBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adaptermodelbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case adaptermodelbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adaptermodelbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adaptermodelbinding.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case adaptermodelbinding.FieldAdapterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field adapter_id", values[i])
			} else if value.Valid {
				_m.AdapterID = int(value.Int64)
			}
		case adaptermodelbinding.FieldSourceModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_model_id", values[i])
			} else if value.Valid {
				_m.SourceModelID = value.String
			}
		case adaptermodelbinding.FieldModelGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_group_id", values[i])
			} else if value.Valid {
				_m.ModelGroupID = int(value.Int64)
			}
		case adaptermodelbinding.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case adaptermodelbinding.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdapterModelBinding.
// This includes values selected through modifiers, order, etc.
func (_m *AdapterModelBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdapter queries the "adapter" edge of the AdapterModelBinding entity.
func (_m *AdapterModelBinding) QueryAdapter() *AdapterQuery {
	return NewAdapterModelBindingClient(_m.config).QueryAdapter(_m)
}

// QueryModelGroup queries the "model_group" edge of the AdapterModelBinding entity.
func (_m *AdapterModelBinding) QueryModelGroup() *ModelGroupQuery {
	return NewAdapterModelBindingClient(_m.config).QueryModelGroup(_m)
}

// Update returns a builder for updating this AdapterModelBinding.
// Note that you need to call AdapterModelBinding.Unwrap() before calling this method if this AdapterModelBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdapterModelBinding) Update() *AdapterModelBindingUpdateOne {
	return NewAdapterModelBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdapterModelBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdapterModelBinding) Unwrap() *AdapterModelBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdapterModelBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdapterModelBinding) String() string {
	var builder strings.Builder
	builder.WriteString("AdapterModelBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("adapter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdapterID))
	builder.WriteString(", ")
	builder.WriteString("source_model_id=")
	builder.WriteString(_m.SourceModelID)
	builder.WriteString(", ")
	builder.WriteString("model_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelGroupID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// AdapterModelBindings is a parsable slice of AdapterModelBinding.
type AdapterModelBindings []*AdapterModelBinding
