// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/adapter"
	"github.com/mutallipp/llm-proxy/internal/ent/adaptermodelbinding"
)

// AdapterCreate is the builder for creating a Adapter entity.
type AdapterCreate struct {
	config
	mutation *AdapterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdapterCreate) SetCreatedAt(v time.Time) *AdapterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdapterCreate) SetNillableCreatedAt(v *time.Time) *AdapterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdapterCreate) SetUpdatedAt(v time.Time) *AdapterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdapterCreate) SetNillableUpdatedAt(v *time.Time) *AdapterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AdapterCreate) SetDeletedAt(v int) *AdapterCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AdapterCreate) SetNillableDeletedAt(v *int) *AdapterCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AdapterCreate) SetName(v string) *AdapterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AdapterCreate) SetDisplayName(v string) *AdapterCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *AdapterCreate) SetNillableDisplayName(v *string) *AdapterCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (_c *AdapterCreate) SetInboundAPIFormat(v string) *AdapterCreate {
	_c.mutation.SetInboundAPIFormat(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AdapterCreate) SetStatus(v adapter.Status) *AdapterCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AdapterCreate) SetNillableStatus(v *adapter.Status) *AdapterCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *AdapterCreate) SetRemark(v string) *AdapterCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *AdapterCreate) SetNillableRemark(v *string) *AdapterCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// AddModelBindingIDs adds the "model_bindings" edge to the AdapterModelBinding entity by IDs.
func (_c *AdapterCreate) AddModelBindingIDs(ids ...int) *AdapterCreate {
	_c.mutation.AddModelBindingIDs(ids...)
	return _c
}

// AddModelBindings adds the "model_bindings" edges to the AdapterModelBinding entity.
func (_c *AdapterCreate) AddModelBindings(v ...*AdapterModelBinding) *AdapterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddModelBindingIDs(ids...)
}

// Mutation returns the AdapterMutation object of the builder.
func (_c *AdapterCreate) Mutation() *AdapterMutation {
	return _c.mutation
}

// Save creates the Adapter in the database.
func (_c *AdapterCreate) Save(ctx context.Context) (*Adapter, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdapterCreate) SaveX(ctx context.Context) *Adapter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdapterCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if adapter.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized adapter.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := adapter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if adapter.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adapter.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adapter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := adapter.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := adapter.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := adapter.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdapterCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Adapter.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Adapter.name"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Adapter.display_name"`)}
	}
	if _, ok := _c.mutation.InboundAPIFormat(); !ok {
		return &ValidationError{Name: "inbound_api_format", err: errors.New(`ent: missing required field "Adapter.inbound_api_format"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Adapter.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := adapter.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Adapter.status": %w`, err)}
		}
	}
	return nil
}

func (_c *AdapterCreate) sqlSave(ctx context.Context) (*Adapter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdapterCreate) createSpec() (*Adapter, *sqlgraph.CreateSpec) {
	var (
		_node = &Adapter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adapter.Table, sqlgraph.NewFieldSpec(adapter.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adapter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adapter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(adapter.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(adapter.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(adapter.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.InboundAPIFormat(); ok {
		_spec.SetField(adapter.FieldInboundAPIFormat, field.TypeString, value)
		_node.InboundAPIFormat = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(adapter.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(adapter.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if nodes := _c.mutation.ModelBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapter.ModelBindingsTable,
			Columns: []string{adapter.ModelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptermodelbinding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Adapter.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterCreate) OnConflict(opts ...sql.ConflictOption) *AdapterUpsertOne {
	_c.conflict = opts
	return &AdapterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Adapter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterCreate) OnConflictColumns(columns ...string) *AdapterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterUpsertOne{
		create: _c,
	}
}

type (
	// AdapterUpsertOne is the builder for "upsert"-ing
	//  one Adapter node.
	AdapterUpsertOne struct {
		create *AdapterCreate
	}

	// AdapterUpsert is the "OnConflict" setter.
	AdapterUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AdapterUpsert) SetUpdatedAt(v time.Time) *AdapterUpsert {
	u.Set(adapter.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdapterUpsert) UpdateUpdatedAt() *AdapterUpsert {
	u.SetExcluded(adapter.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdapterUpsert) SetDeletedAt(v int) *AdapterUpsert {
	u.Set(adapter.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdapterUpsert) UpdateDeletedAt() *AdapterUpsert {
	u.SetExcluded(adapter.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AdapterUpsert) AddDeletedAt(v int) *AdapterUpsert {
	u.Add(adapter.FieldDeletedAt, v)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *AdapterUpsert) SetDisplayName(v string) *AdapterUpsert {
	u.Set(adapter.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AdapterUpsert) UpdateDisplayName() *AdapterUpsert {
	u.SetExcluded(adapter.FieldDisplayName)
	return u
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (u *AdapterUpsert) SetInboundAPIFormat(v string) *AdapterUpsert {
	u.Set(adapter.FieldInboundAPIFormat, v)
	return u
}

// UpdateInboundAPIFormat sets the "inbound_api_format" field to the value that was provided on create.
func (u *AdapterUpsert) UpdateInboundAPIFormat() *AdapterUpsert {
	u.SetExcluded(adapter.FieldInboundAPIFormat)
	return u
}

// SetStatus sets the "status" field.
func (u *AdapterUpsert) SetStatus(v adapter.Status) *AdapterUpsert {
	u.Set(adapter.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdapterUpsert) UpdateStatus() *AdapterUpsert {
	u.SetExcluded(adapter.FieldStatus)
	return u
}

// SetRemark sets the "remark" field.
func (u *AdapterUpsert) SetRemark(v string) *AdapterUpsert {
	u.Set(adapter.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AdapterUpsert) UpdateRemark() *AdapterUpsert {
	u.SetExcluded(adapter.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *AdapterUpsert) ClearRemark() *AdapterUpsert {
	u.SetNull(adapter.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Adapter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterUpsertOne) UpdateNewValues() *AdapterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adapter.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(adapter.FieldName)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Adapter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdapterUpsertOne) Ignore() *AdapterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterUpsertOne) DoNothing() *AdapterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterCreate.OnConflict
// documentation for more info.
func (u *AdapterUpsertOne) Update(set func(*AdapterUpsert)) *AdapterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdapterUpsertOne) SetUpdatedAt(v time.Time) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdapterUpsertOne) UpdateUpdatedAt() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdapterUpsertOne) SetDeletedAt(v int) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AdapterUpsertOne) AddDeletedAt(v int) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdapterUpsertOne) UpdateDeletedAt() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *AdapterUpsertOne) SetDisplayName(v string) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AdapterUpsertOne) UpdateDisplayName() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateDisplayName()
	})
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (u *AdapterUpsertOne) SetInboundAPIFormat(v string) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.SetInboundAPIFormat(v)
	})
}

// UpdateInboundAPIFormat sets the "inbound_api_format" field to the value that was provided on create.
func (u *AdapterUpsertOne) UpdateInboundAPIFormat() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateInboundAPIFormat()
	})
}

// SetStatus sets the "status" field.
func (u *AdapterUpsertOne) SetStatus(v adapter.Status) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdapterUpsertOne) UpdateStatus() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateStatus()
	})
}

// SetRemark sets the "remark" field.
func (u *AdapterUpsertOne) SetRemark(v string) *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AdapterUpsertOne) UpdateRemark() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *AdapterUpsertOne) ClearRemark() *AdapterUpsertOne {
	return u.Update(func(s *AdapterUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *AdapterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdapterUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdapterUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdapterCreateBulk is the builder for creating many Adapter entities in bulk.
type AdapterCreateBulk struct {
	config
	err      error
	builders []*AdapterCreate
	conflict []sql.ConflictOption
}

// Save creates the Adapter entities in the database.
func (_c *AdapterCreateBulk) Save(ctx context.Context) ([]*Adapter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Adapter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdapterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdapterCreateBulk) SaveX(ctx context.Context) []*Adapter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Adapter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdapterUpsertBulk {
	_c.conflict = opts
	return &AdapterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Adapter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterCreateBulk) OnConflictColumns(columns ...string) *AdapterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterUpsertBulk{
		create: _c,
	}
}

// AdapterUpsertBulk is the builder for "upsert"-ing
// a bulk of Adapter nodes.
type AdapterUpsertBulk struct {
	create *AdapterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Adapter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterUpsertBulk) UpdateNewValues() *AdapterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adapter.FieldCreatedAt)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(adapter.FieldName)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Adapter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdapterUpsertBulk) Ignore() *AdapterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterUpsertBulk) DoNothing() *AdapterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterCreateBulk.OnConflict
// documentation for more info.
func (u *AdapterUpsertBulk) Update(set func(*AdapterUpsert)) *AdapterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdapterUpsertBulk) SetUpdatedAt(v time.Time) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdapterUpsertBulk) UpdateUpdatedAt() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdapterUpsertBulk) SetDeletedAt(v int) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AdapterUpsertBulk) AddDeletedAt(v int) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdapterUpsertBulk) UpdateDeletedAt() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *AdapterUpsertBulk) SetDisplayName(v string) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AdapterUpsertBulk) UpdateDisplayName() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateDisplayName()
	})
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (u *AdapterUpsertBulk) SetInboundAPIFormat(v string) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.SetInboundAPIFormat(v)
	})
}

// UpdateInboundAPIFormat sets the "inbound_api_format" field to the value that was provided on create.
func (u *AdapterUpsertBulk) UpdateInboundAPIFormat() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateInboundAPIFormat()
	})
}

// SetStatus sets the "status" field.
func (u *AdapterUpsertBulk) SetStatus(v adapter.Status) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdapterUpsertBulk) UpdateStatus() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateStatus()
	})
}

// SetRemark sets the "remark" field.
func (u *AdapterUpsertBulk) SetRemark(v string) *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AdapterUpsertBulk) UpdateRemark() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *AdapterUpsertBulk) ClearRemark() *AdapterUpsertBulk {
	return u.Update(func(s *AdapterUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *AdapterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdapterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
