// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroup"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroupprotocol"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgrouptarget"
)

// ModelGroupProtocolCreate is the builder for creating a ModelGroupProtocol entity.
type ModelGroupProtocolCreate struct {
	config
	mutation *ModelGroupProtocolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelGroupProtocolCreate) SetCreatedAt(v time.Time) *ModelGroupProtocolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelGroupProtocolCreate) SetNillableCreatedAt(v *time.Time) *ModelGroupProtocolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelGroupProtocolCreate) SetUpdatedAt(v time.Time) *ModelGroupProtocolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelGroupProtocolCreate) SetNillableUpdatedAt(v *time.Time) *ModelGroupProtocolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ModelGroupProtocolCreate) SetDeletedAt(v int) *ModelGroupProtocolCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ModelGroupProtocolCreate) SetNillableDeletedAt(v *int) *ModelGroupProtocolCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetModelGroupID sets the "model_group_id" field.
func (_c *ModelGroupProtocolCreate) SetModelGroupID(v int) *ModelGroupProtocolCreate {
	_c.mutation.SetModelGroupID(v)
	return _c
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (_c *ModelGroupProtocolCreate) SetInboundAPIFormat(v string) *ModelGroupProtocolCreate {
	_c.mutation.SetInboundAPIFormat(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ModelGroupProtocolCreate) SetEnabled(v bool) *ModelGroupProtocolCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ModelGroupProtocolCreate) SetNillableEnabled(v *bool) *ModelGroupProtocolCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ModelGroupProtocolCreate) SetRemark(v string) *ModelGroupProtocolCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ModelGroupProtocolCreate) SetNillableRemark(v *string) *ModelGroupProtocolCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetModelGroup sets the "model_group" edge to the ModelGroup entity.
func (_c *ModelGroupProtocolCreate) SetModelGroup(v *ModelGroup) *ModelGroupProtocolCreate {
	return _c.SetModelGroupID(v.ID)
}

// AddTargetIDs adds the "targets" edge to the ModelGroupTarget entity by IDs.
func (_c *ModelGroupProtocolCreate) AddTargetIDs(ids ...int) *ModelGroupProtocolCreate {
	_c.mutation.AddTargetIDs(ids...)
	return _c
}

// AddTargets adds the "targets" edges to the ModelGroupTarget entity.
func (_c *ModelGroupProtocolCreate) AddTargets(v ...*ModelGroupTarget) *ModelGroupProtocolCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTargetIDs(ids...)
}

// Mutation returns the ModelGroupProtocolMutation object of the builder.
func (_c *ModelGroupProtocolCreate) Mutation() *ModelGroupProtocolMutation {
	return _c.mutation
}

// Save creates the ModelGroupProtocol in the database.
func (_c *ModelGroupProtocolCreate) Save(ctx context.Context) (*ModelGroupProtocol, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelGroupProtocolCreate) SaveX(ctx context.Context) *ModelGroupProtocol {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelGroupProtocolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelGroupProtocolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelGroupProtocolCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if modelgroupprotocol.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroupprotocol.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroupprotocol.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if modelgroupprotocol.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroupprotocol.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroupprotocol.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := modelgroupprotocol.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := modelgroupprotocol.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelGroupProtocolCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "ModelGroupProtocol.deleted_at"`)}
	}
	if _, ok := _c.mutation.ModelGroupID(); !ok {
		return &ValidationError{Name: "model_group_id", err: errors.New(`ent: missing required field "ModelGroupProtocol.model_group_id"`)}
	}
	if _, ok := _c.mutation.InboundAPIFormat(); !ok {
		return &ValidationError{Name: "inbound_api_format", err: errors.New(`ent: missing required field "ModelGroupProtocol.inbound_api_format"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ModelGroupProtocol.enabled"`)}
	}
	if len(_c.mutation.ModelGroupIDs()) == 0 {
		return &ValidationError{Name: "model_group", err: errors.New(`ent: missing required edge "ModelGroupProtocol.model_group"`)}
	}
	return nil
}

func (_c *ModelGroupProtocolCreate) sqlSave(ctx context.Context) (*ModelGroupProtocol, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelGroupProtocolCreate) createSpec() (*ModelGroupProtocol, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelGroupProtocol{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelgroupprotocol.Table, sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.InboundAPIFormat(); ok {
		_spec.SetField(modelgroupprotocol.FieldInboundAPIFormat, field.TypeString, value)
		_node.InboundAPIFormat = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(modelgroupprotocol.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(modelgroupprotocol.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if nodes := _c.mutation.ModelGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelgroupprotocol.ModelGroupTable,
			Columns: []string{modelgroupprotocol.ModelGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelGroupProtocol.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelGroupProtocolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelGroupProtocolCreate) OnConflict(opts ...sql.ConflictOption) *ModelGroupProtocolUpsertOne {
	_c.conflict = opts
	return &ModelGroupProtocolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelGroupProtocol.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelGroupProtocolCreate) OnConflictColumns(columns ...string) *ModelGroupProtocolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelGroupProtocolUpsertOne{
		create: _c,
	}
}

type (
	// ModelGroupProtocolUpsertOne is the builder for "upsert"-ing
	//  one ModelGroupProtocol node.
	ModelGroupProtocolUpsertOne struct {
		create *ModelGroupProtocolCreate
	}

	// ModelGroupProtocolUpsert is the "OnConflict" setter.
	ModelGroupProtocolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupProtocolUpsert) SetUpdatedAt(v time.Time) *ModelGroupProtocolUpsert {
	u.Set(modelgroupprotocol.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsert) UpdateUpdatedAt() *ModelGroupProtocolUpsert {
	u.SetExcluded(modelgroupprotocol.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupProtocolUpsert) SetDeletedAt(v int) *ModelGroupProtocolUpsert {
	u.Set(modelgroupprotocol.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsert) UpdateDeletedAt() *ModelGroupProtocolUpsert {
	u.SetExcluded(modelgroupprotocol.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupProtocolUpsert) AddDeletedAt(v int) *ModelGroupProtocolUpsert {
	u.Add(modelgroupprotocol.FieldDeletedAt, v)
	return u
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (u *ModelGroupProtocolUpsert) SetInboundAPIFormat(v string) *ModelGroupProtocolUpsert {
	u.Set(modelgroupprotocol.FieldInboundAPIFormat, v)
	return u
}

// UpdateInboundAPIFormat sets the "inbound_api_format" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsert) UpdateInboundAPIFormat() *ModelGroupProtocolUpsert {
	u.SetExcluded(modelgroupprotocol.FieldInboundAPIFormat)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ModelGroupProtocolUpsert) SetEnabled(v bool) *ModelGroupProtocolUpsert {
	u.Set(modelgroupprotocol.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsert) UpdateEnabled() *ModelGroupProtocolUpsert {
	u.SetExcluded(modelgroupprotocol.FieldEnabled)
	return u
}

// SetRemark sets the "remark" field.
func (u *ModelGroupProtocolUpsert) SetRemark(v string) *ModelGroupProtocolUpsert {
	u.Set(modelgroupprotocol.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsert) UpdateRemark() *ModelGroupProtocolUpsert {
	u.SetExcluded(modelgroupprotocol.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupProtocolUpsert) ClearRemark() *ModelGroupProtocolUpsert {
	u.SetNull(modelgroupprotocol.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelGroupProtocol.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelGroupProtocolUpsertOne) UpdateNewValues() *ModelGroupProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelgroupprotocol.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ModelGroupID(); exists {
			s.SetIgnore(modelgroupprotocol.FieldModelGroupID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelGroupProtocol.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelGroupProtocolUpsertOne) Ignore() *ModelGroupProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelGroupProtocolUpsertOne) DoNothing() *ModelGroupProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelGroupProtocolCreate.OnConflict
// documentation for more info.
func (u *ModelGroupProtocolUpsertOne) Update(set func(*ModelGroupProtocolUpsert)) *ModelGroupProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelGroupProtocolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupProtocolUpsertOne) SetUpdatedAt(v time.Time) *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertOne) UpdateUpdatedAt() *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupProtocolUpsertOne) SetDeletedAt(v int) *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupProtocolUpsertOne) AddDeletedAt(v int) *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertOne) UpdateDeletedAt() *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (u *ModelGroupProtocolUpsertOne) SetInboundAPIFormat(v string) *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetInboundAPIFormat(v)
	})
}

// UpdateInboundAPIFormat sets the "inbound_api_format" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertOne) UpdateInboundAPIFormat() *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateInboundAPIFormat()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ModelGroupProtocolUpsertOne) SetEnabled(v bool) *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertOne) UpdateEnabled() *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelGroupProtocolUpsertOne) SetRemark(v string) *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertOne) UpdateRemark() *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupProtocolUpsertOne) ClearRemark() *ModelGroupProtocolUpsertOne {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelGroupProtocolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelGroupProtocolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelGroupProtocolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelGroupProtocolUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelGroupProtocolUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelGroupProtocolCreateBulk is the builder for creating many ModelGroupProtocol entities in bulk.
type ModelGroupProtocolCreateBulk struct {
	config
	err      error
	builders []*ModelGroupProtocolCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelGroupProtocol entities in the database.
func (_c *ModelGroupProtocolCreateBulk) Save(ctx context.Context) ([]*ModelGroupProtocol, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelGroupProtocol, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelGroupProtocolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelGroupProtocolCreateBulk) SaveX(ctx context.Context) []*ModelGroupProtocol {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelGroupProtocolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelGroupProtocolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelGroupProtocol.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelGroupProtocolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelGroupProtocolCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelGroupProtocolUpsertBulk {
	_c.conflict = opts
	return &ModelGroupProtocolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelGroupProtocol.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelGroupProtocolCreateBulk) OnConflictColumns(columns ...string) *ModelGroupProtocolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelGroupProtocolUpsertBulk{
		create: _c,
	}
}

// ModelGroupProtocolUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelGroupProtocol nodes.
type ModelGroupProtocolUpsertBulk struct {
	create *ModelGroupProtocolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelGroupProtocol.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelGroupProtocolUpsertBulk) UpdateNewValues() *ModelGroupProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelgroupprotocol.FieldCreatedAt)
			}
			if _, exists := b.mutation.ModelGroupID(); exists {
				s.SetIgnore(modelgroupprotocol.FieldModelGroupID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelGroupProtocol.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelGroupProtocolUpsertBulk) Ignore() *ModelGroupProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelGroupProtocolUpsertBulk) DoNothing() *ModelGroupProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelGroupProtocolCreateBulk.OnConflict
// documentation for more info.
func (u *ModelGroupProtocolUpsertBulk) Update(set func(*ModelGroupProtocolUpsert)) *ModelGroupProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelGroupProtocolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupProtocolUpsertBulk) SetUpdatedAt(v time.Time) *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertBulk) UpdateUpdatedAt() *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupProtocolUpsertBulk) SetDeletedAt(v int) *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupProtocolUpsertBulk) AddDeletedAt(v int) *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertBulk) UpdateDeletedAt() *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (u *ModelGroupProtocolUpsertBulk) SetInboundAPIFormat(v string) *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetInboundAPIFormat(v)
	})
}

// UpdateInboundAPIFormat sets the "inbound_api_format" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertBulk) UpdateInboundAPIFormat() *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateInboundAPIFormat()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ModelGroupProtocolUpsertBulk) SetEnabled(v bool) *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertBulk) UpdateEnabled() *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelGroupProtocolUpsertBulk) SetRemark(v string) *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupProtocolUpsertBulk) UpdateRemark() *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupProtocolUpsertBulk) ClearRemark() *ModelGroupProtocolUpsertBulk {
	return u.Update(func(s *ModelGroupProtocolUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelGroupProtocolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelGroupProtocolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelGroupProtocolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelGroupProtocolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
