// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/adaptermodelbinding"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroup"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroupprotocol"
)

// ModelGroupCreate is the builder for creating a ModelGroup entity.
type ModelGroupCreate struct {
	config
	mutation *ModelGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelGroupCreate) SetCreatedAt(v time.Time) *ModelGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableCreatedAt(v *time.Time) *ModelGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelGroupCreate) SetUpdatedAt(v time.Time) *ModelGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableUpdatedAt(v *time.Time) *ModelGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ModelGroupCreate) SetDeletedAt(v int) *ModelGroupCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableDeletedAt(v *int) *ModelGroupCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ModelGroupCreate) SetName(v string) *ModelGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ModelGroupCreate) SetDisplayName(v string) *ModelGroupCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableDisplayName(v *string) *ModelGroupCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelGroupCreate) SetStatus(v modelgroup.Status) *ModelGroupCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableStatus(v *modelgroup.Status) *ModelGroupCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (_c *ModelGroupCreate) SetSelectionStrategy(v modelgroup.SelectionStrategy) *ModelGroupCreate {
	_c.mutation.SetSelectionStrategy(v)
	return _c
}

// SetNillableSelectionStrategy sets the "selection_strategy" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableSelectionStrategy(v *modelgroup.SelectionStrategy) *ModelGroupCreate {
	if v != nil {
		_c.SetSelectionStrategy(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ModelGroupCreate) SetRemark(v string) *ModelGroupCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ModelGroupCreate) SetNillableRemark(v *string) *ModelGroupCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// AddAdapterBindingIDs adds the "adapter_bindings" edge to the AdapterModelBinding entity by IDs.
func (_c *ModelGroupCreate) AddAdapterBindingIDs(ids ...int) *ModelGroupCreate {
	_c.mutation.AddAdapterBindingIDs(ids...)
	return _c
}

// AddAdapterBindings adds the "adapter_bindings" edges to the AdapterModelBinding entity.
func (_c *ModelGroupCreate) AddAdapterBindings(v ...*AdapterModelBinding) *ModelGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAdapterBindingIDs(ids...)
}

// AddProtocolIDs adds the "protocols" edge to the ModelGroupProtocol entity by IDs.
func (_c *ModelGroupCreate) AddProtocolIDs(ids ...int) *ModelGroupCreate {
	_c.mutation.AddProtocolIDs(ids...)
	return _c
}

// AddProtocols adds the "protocols" edges to the ModelGroupProtocol entity.
func (_c *ModelGroupCreate) AddProtocols(v ...*ModelGroupProtocol) *ModelGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProtocolIDs(ids...)
}

// Mutation returns the ModelGroupMutation object of the builder.
func (_c *ModelGroupCreate) Mutation() *ModelGroupMutation {
	return _c.mutation
}

// Save creates the ModelGroup in the database.
func (_c *ModelGroupCreate) Save(ctx context.Context) (*ModelGroup, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelGroupCreate) SaveX(ctx context.Context) *ModelGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelGroupCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if modelgroup.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroup.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if modelgroup.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroup.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := modelgroup.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := modelgroup.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := modelgroup.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SelectionStrategy(); !ok {
		v := modelgroup.DefaultSelectionStrategy
		_c.mutation.SetSelectionStrategy(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelGroupCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "ModelGroup.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ModelGroup.name"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "ModelGroup.display_name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelGroup.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := modelgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelGroup.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SelectionStrategy(); !ok {
		return &ValidationError{Name: "selection_strategy", err: errors.New(`ent: missing required field "ModelGroup.selection_strategy"`)}
	}
	if v, ok := _c.mutation.SelectionStrategy(); ok {
		if err := modelgroup.SelectionStrategyValidator(v); err != nil {
			return &ValidationError{Name: "selection_strategy", err: fmt.Errorf(`ent: validator failed for field "ModelGroup.selection_strategy": %w`, err)}
		}
	}
	return nil
}

func (_c *ModelGroupCreate) sqlSave(ctx context.Context) (*ModelGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelGroupCreate) createSpec() (*ModelGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelgroup.Table, sqlgraph.NewFieldSpec(modelgroup.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(modelgroup.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(modelgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(modelgroup.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelgroup.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SelectionStrategy(); ok {
		_spec.SetField(modelgroup.FieldSelectionStrategy, field.TypeEnum, value)
		_node.SelectionStrategy = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(modelgroup.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if nodes := _c.mutation.AdapterBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.AdapterBindingsTable,
			Columns: []string{modelgroup.AdapterBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adaptermodelbinding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProtocolsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelGroupCreate) OnConflict(opts ...sql.ConflictOption) *ModelGroupUpsertOne {
	_c.conflict = opts
	return &ModelGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelGroupCreate) OnConflictColumns(columns ...string) *ModelGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelGroupUpsertOne{
		create: _c,
	}
}

type (
	// ModelGroupUpsertOne is the builder for "upsert"-ing
	//  one ModelGroup node.
	ModelGroupUpsertOne struct {
		create *ModelGroupCreate
	}

	// ModelGroupUpsert is the "OnConflict" setter.
	ModelGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupUpsert) SetUpdatedAt(v time.Time) *ModelGroupUpsert {
	u.Set(modelgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateUpdatedAt() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupUpsert) SetDeletedAt(v int) *ModelGroupUpsert {
	u.Set(modelgroup.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateDeletedAt() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupUpsert) AddDeletedAt(v int) *ModelGroupUpsert {
	u.Add(modelgroup.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *ModelGroupUpsert) SetName(v string) *ModelGroupUpsert {
	u.Set(modelgroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateName() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldName)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *ModelGroupUpsert) SetDisplayName(v string) *ModelGroupUpsert {
	u.Set(modelgroup.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateDisplayName() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldDisplayName)
	return u
}

// SetStatus sets the "status" field.
func (u *ModelGroupUpsert) SetStatus(v modelgroup.Status) *ModelGroupUpsert {
	u.Set(modelgroup.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateStatus() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldStatus)
	return u
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (u *ModelGroupUpsert) SetSelectionStrategy(v modelgroup.SelectionStrategy) *ModelGroupUpsert {
	u.Set(modelgroup.FieldSelectionStrategy, v)
	return u
}

// UpdateSelectionStrategy sets the "selection_strategy" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateSelectionStrategy() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldSelectionStrategy)
	return u
}

// SetRemark sets the "remark" field.
func (u *ModelGroupUpsert) SetRemark(v string) *ModelGroupUpsert {
	u.Set(modelgroup.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupUpsert) UpdateRemark() *ModelGroupUpsert {
	u.SetExcluded(modelgroup.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupUpsert) ClearRemark() *ModelGroupUpsert {
	u.SetNull(modelgroup.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelGroupUpsertOne) UpdateNewValues() *ModelGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelGroupUpsertOne) Ignore() *ModelGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelGroupUpsertOne) DoNothing() *ModelGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelGroupCreate.OnConflict
// documentation for more info.
func (u *ModelGroupUpsertOne) Update(set func(*ModelGroupUpsert)) *ModelGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupUpsertOne) SetUpdatedAt(v time.Time) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateUpdatedAt() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupUpsertOne) SetDeletedAt(v int) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupUpsertOne) AddDeletedAt(v int) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateDeletedAt() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ModelGroupUpsertOne) SetName(v string) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateName() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ModelGroupUpsertOne) SetDisplayName(v string) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateDisplayName() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateDisplayName()
	})
}

// SetStatus sets the "status" field.
func (u *ModelGroupUpsertOne) SetStatus(v modelgroup.Status) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateStatus() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateStatus()
	})
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (u *ModelGroupUpsertOne) SetSelectionStrategy(v modelgroup.SelectionStrategy) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetSelectionStrategy(v)
	})
}

// UpdateSelectionStrategy sets the "selection_strategy" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateSelectionStrategy() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateSelectionStrategy()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelGroupUpsertOne) SetRemark(v string) *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupUpsertOne) UpdateRemark() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupUpsertOne) ClearRemark() *ModelGroupUpsertOne {
	return u.Update(func(s *ModelGroupUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelGroupUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelGroupUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelGroupCreateBulk is the builder for creating many ModelGroup entities in bulk.
type ModelGroupCreateBulk struct {
	config
	err      error
	builders []*ModelGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelGroup entities in the database.
func (_c *ModelGroupCreateBulk) Save(ctx context.Context) ([]*ModelGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelGroupCreateBulk) SaveX(ctx context.Context) []*ModelGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelGroupUpsertBulk {
	_c.conflict = opts
	return &ModelGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelGroupCreateBulk) OnConflictColumns(columns ...string) *ModelGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelGroupUpsertBulk{
		create: _c,
	}
}

// ModelGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelGroup nodes.
type ModelGroupUpsertBulk struct {
	create *ModelGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelGroupUpsertBulk) UpdateNewValues() *ModelGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelGroupUpsertBulk) Ignore() *ModelGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelGroupUpsertBulk) DoNothing() *ModelGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelGroupCreateBulk.OnConflict
// documentation for more info.
func (u *ModelGroupUpsertBulk) Update(set func(*ModelGroupUpsert)) *ModelGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupUpsertBulk) SetUpdatedAt(v time.Time) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateUpdatedAt() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupUpsertBulk) SetDeletedAt(v int) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupUpsertBulk) AddDeletedAt(v int) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateDeletedAt() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ModelGroupUpsertBulk) SetName(v string) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateName() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ModelGroupUpsertBulk) SetDisplayName(v string) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateDisplayName() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateDisplayName()
	})
}

// SetStatus sets the "status" field.
func (u *ModelGroupUpsertBulk) SetStatus(v modelgroup.Status) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateStatus() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateStatus()
	})
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (u *ModelGroupUpsertBulk) SetSelectionStrategy(v modelgroup.SelectionStrategy) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetSelectionStrategy(v)
	})
}

// UpdateSelectionStrategy sets the "selection_strategy" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateSelectionStrategy() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateSelectionStrategy()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelGroupUpsertBulk) SetRemark(v string) *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupUpsertBulk) UpdateRemark() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupUpsertBulk) ClearRemark() *ModelGroupUpsertBulk {
	return u.Update(func(s *ModelGroupUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
