// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/modelgrouptarget"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// ModelGroupTargetUpdate is the builder for updating ModelGroupTarget entities.
type ModelGroupTargetUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelGroupTargetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelGroupTargetUpdate builder.
func (_u *ModelGroupTargetUpdate) Where(ps ...predicate.ModelGroupTarget) *ModelGroupTargetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelGroupTargetUpdate) SetUpdatedAt(v time.Time) *ModelGroupTargetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelGroupTargetUpdate) SetDeletedAt(v int) *ModelGroupTargetUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillableDeletedAt(v *int) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ModelGroupTargetUpdate) AddDeletedAt(v int) *ModelGroupTargetUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetTargetModelID sets the "target_model_id" field.
func (_u *ModelGroupTargetUpdate) SetTargetModelID(v string) *ModelGroupTargetUpdate {
	_u.mutation.SetTargetModelID(v)
	return _u
}

// SetNillableTargetModelID sets the "target_model_id" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillableTargetModelID(v *string) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetTargetModelID(*v)
	}
	return _u
}

// SetOutboundAPIFormat sets the "outbound_api_format" field.
func (_u *ModelGroupTargetUpdate) SetOutboundAPIFormat(v string) *ModelGroupTargetUpdate {
	_u.mutation.SetOutboundAPIFormat(v)
	return _u
}

// SetNillableOutboundAPIFormat sets the "outbound_api_format" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillableOutboundAPIFormat(v *string) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetOutboundAPIFormat(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ModelGroupTargetUpdate) SetPriority(v int) *ModelGroupTargetUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillablePriority(v *int) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ModelGroupTargetUpdate) AddPriority(v int) *ModelGroupTargetUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelGroupTargetUpdate) SetEnabled(v bool) *ModelGroupTargetUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillableEnabled(v *bool) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelGroupTargetUpdate) SetCapabilities(v objects.AdapterTargetCapabilities) *ModelGroupTargetUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetNillableCapabilities sets the "capabilities" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillableCapabilities(v *objects.AdapterTargetCapabilities) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetCapabilities(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelGroupTargetUpdate) SetRemark(v string) *ModelGroupTargetUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelGroupTargetUpdate) SetNillableRemark(v *string) *ModelGroupTargetUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelGroupTargetUpdate) ClearRemark() *ModelGroupTargetUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// Mutation returns the ModelGroupTargetMutation object of the builder.
func (_u *ModelGroupTargetUpdate) Mutation() *ModelGroupTargetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelGroupTargetUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelGroupTargetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelGroupTargetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelGroupTargetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelGroupTargetUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelgrouptarget.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgrouptarget.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgrouptarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelGroupTargetUpdate) check() error {
	if _u.mutation.ModelGroupProtocolCleared() && len(_u.mutation.ModelGroupProtocolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelGroupTarget.model_group_protocol"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelGroupTarget.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelGroupTargetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelGroupTargetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelGroupTargetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelgrouptarget.Table, modelgrouptarget.Columns, sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(modelgrouptarget.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetModelID(); ok {
		_spec.SetField(modelgrouptarget.FieldTargetModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutboundAPIFormat(); ok {
		_spec.SetField(modelgrouptarget.FieldOutboundAPIFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(modelgrouptarget.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(modelgrouptarget.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelgrouptarget.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(modelgrouptarget.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(modelgrouptarget.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(modelgrouptarget.FieldRemark, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelgrouptarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelGroupTargetUpdateOne is the builder for updating a single ModelGroupTarget entity.
type ModelGroupTargetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelGroupTargetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelGroupTargetUpdateOne) SetUpdatedAt(v time.Time) *ModelGroupTargetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelGroupTargetUpdateOne) SetDeletedAt(v int) *ModelGroupTargetUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillableDeletedAt(v *int) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ModelGroupTargetUpdateOne) AddDeletedAt(v int) *ModelGroupTargetUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetTargetModelID sets the "target_model_id" field.
func (_u *ModelGroupTargetUpdateOne) SetTargetModelID(v string) *ModelGroupTargetUpdateOne {
	_u.mutation.SetTargetModelID(v)
	return _u
}

// SetNillableTargetModelID sets the "target_model_id" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillableTargetModelID(v *string) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetTargetModelID(*v)
	}
	return _u
}

// SetOutboundAPIFormat sets the "outbound_api_format" field.
func (_u *ModelGroupTargetUpdateOne) SetOutboundAPIFormat(v string) *ModelGroupTargetUpdateOne {
	_u.mutation.SetOutboundAPIFormat(v)
	return _u
}

// SetNillableOutboundAPIFormat sets the "outbound_api_format" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillableOutboundAPIFormat(v *string) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetOutboundAPIFormat(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ModelGroupTargetUpdateOne) SetPriority(v int) *ModelGroupTargetUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillablePriority(v *int) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ModelGroupTargetUpdateOne) AddPriority(v int) *ModelGroupTargetUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelGroupTargetUpdateOne) SetEnabled(v bool) *ModelGroupTargetUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillableEnabled(v *bool) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelGroupTargetUpdateOne) SetCapabilities(v objects.AdapterTargetCapabilities) *ModelGroupTargetUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetNillableCapabilities sets the "capabilities" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillableCapabilities(v *objects.AdapterTargetCapabilities) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetCapabilities(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelGroupTargetUpdateOne) SetRemark(v string) *ModelGroupTargetUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelGroupTargetUpdateOne) SetNillableRemark(v *string) *ModelGroupTargetUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelGroupTargetUpdateOne) ClearRemark() *ModelGroupTargetUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// Mutation returns the ModelGroupTargetMutation object of the builder.
func (_u *ModelGroupTargetUpdateOne) Mutation() *ModelGroupTargetMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelGroupTargetUpdate builder.
func (_u *ModelGroupTargetUpdateOne) Where(ps ...predicate.ModelGroupTarget) *ModelGroupTargetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelGroupTargetUpdateOne) Select(field string, fields ...string) *ModelGroupTargetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelGroupTarget entity.
func (_u *ModelGroupTargetUpdateOne) Save(ctx context.Context) (*ModelGroupTarget, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelGroupTargetUpdateOne) SaveX(ctx context.Context) *ModelGroupTarget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelGroupTargetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelGroupTargetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelGroupTargetUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelgrouptarget.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgrouptarget.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgrouptarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelGroupTargetUpdateOne) check() error {
	if _u.mutation.ModelGroupProtocolCleared() && len(_u.mutation.ModelGroupProtocolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelGroupTarget.model_group_protocol"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelGroupTarget.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelGroupTargetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelGroupTargetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelGroupTargetUpdateOne) sqlSave(ctx context.Context) (_node *ModelGroupTarget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelgrouptarget.Table, modelgrouptarget.Columns, sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelGroupTarget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelgrouptarget.FieldID)
		for _, f := range fields {
			if !modelgrouptarget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelgrouptarget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(modelgrouptarget.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetModelID(); ok {
		_spec.SetField(modelgrouptarget.FieldTargetModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutboundAPIFormat(); ok {
		_spec.SetField(modelgrouptarget.FieldOutboundAPIFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(modelgrouptarget.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(modelgrouptarget.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelgrouptarget.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(modelgrouptarget.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(modelgrouptarget.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(modelgrouptarget.FieldRemark, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelGroupTarget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelgrouptarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
