// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelgroupprotocol"
	"github.com/looplj/axonhub/internal/ent/modelgrouptarget"
	"github.com/looplj/axonhub/internal/objects"
)

// ModelGroupTargetCreate is the builder for creating a ModelGroupTarget entity.
type ModelGroupTargetCreate struct {
	config
	mutation *ModelGroupTargetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelGroupTargetCreate) SetCreatedAt(v time.Time) *ModelGroupTargetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillableCreatedAt(v *time.Time) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelGroupTargetCreate) SetUpdatedAt(v time.Time) *ModelGroupTargetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillableUpdatedAt(v *time.Time) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ModelGroupTargetCreate) SetDeletedAt(v int) *ModelGroupTargetCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillableDeletedAt(v *int) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetModelGroupProtocolID sets the "model_group_protocol_id" field.
func (_c *ModelGroupTargetCreate) SetModelGroupProtocolID(v int) *ModelGroupTargetCreate {
	_c.mutation.SetModelGroupProtocolID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ModelGroupTargetCreate) SetChannelID(v int) *ModelGroupTargetCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetTargetModelID sets the "target_model_id" field.
func (_c *ModelGroupTargetCreate) SetTargetModelID(v string) *ModelGroupTargetCreate {
	_c.mutation.SetTargetModelID(v)
	return _c
}

// SetOutboundAPIFormat sets the "outbound_api_format" field.
func (_c *ModelGroupTargetCreate) SetOutboundAPIFormat(v string) *ModelGroupTargetCreate {
	_c.mutation.SetOutboundAPIFormat(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ModelGroupTargetCreate) SetPriority(v int) *ModelGroupTargetCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillablePriority(v *int) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ModelGroupTargetCreate) SetEnabled(v bool) *ModelGroupTargetCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillableEnabled(v *bool) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *ModelGroupTargetCreate) SetCapabilities(v objects.AdapterTargetCapabilities) *ModelGroupTargetCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetNillableCapabilities sets the "capabilities" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillableCapabilities(v *objects.AdapterTargetCapabilities) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetCapabilities(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ModelGroupTargetCreate) SetRemark(v string) *ModelGroupTargetCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ModelGroupTargetCreate) SetNillableRemark(v *string) *ModelGroupTargetCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetModelGroupProtocol sets the "model_group_protocol" edge to the ModelGroupProtocol entity.
func (_c *ModelGroupTargetCreate) SetModelGroupProtocol(v *ModelGroupProtocol) *ModelGroupTargetCreate {
	return _c.SetModelGroupProtocolID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ModelGroupTargetCreate) SetChannel(v *Channel) *ModelGroupTargetCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ModelGroupTargetMutation object of the builder.
func (_c *ModelGroupTargetCreate) Mutation() *ModelGroupTargetMutation {
	return _c.mutation
}

// Save creates the ModelGroupTarget in the database.
func (_c *ModelGroupTargetCreate) Save(ctx context.Context) (*ModelGroupTarget, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelGroupTargetCreate) SaveX(ctx context.Context) *ModelGroupTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelGroupTargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelGroupTargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelGroupTargetCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if modelgrouptarget.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgrouptarget.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := modelgrouptarget.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if modelgrouptarget.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgrouptarget.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgrouptarget.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := modelgrouptarget.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := modelgrouptarget.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := modelgrouptarget.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		v := modelgrouptarget.DefaultCapabilities
		_c.mutation.SetCapabilities(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelGroupTargetCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "ModelGroupTarget.deleted_at"`)}
	}
	if _, ok := _c.mutation.ModelGroupProtocolID(); !ok {
		return &ValidationError{Name: "model_group_protocol_id", err: errors.New(`ent: missing required field "ModelGroupTarget.model_group_protocol_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ModelGroupTarget.channel_id"`)}
	}
	if _, ok := _c.mutation.TargetModelID(); !ok {
		return &ValidationError{Name: "target_model_id", err: errors.New(`ent: missing required field "ModelGroupTarget.target_model_id"`)}
	}
	if _, ok := _c.mutation.OutboundAPIFormat(); !ok {
		return &ValidationError{Name: "outbound_api_format", err: errors.New(`ent: missing required field "ModelGroupTarget.outbound_api_format"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "ModelGroupTarget.priority"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ModelGroupTarget.enabled"`)}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "ModelGroupTarget.capabilities"`)}
	}
	if len(_c.mutation.ModelGroupProtocolIDs()) == 0 {
		return &ValidationError{Name: "model_group_protocol", err: errors.New(`ent: missing required edge "ModelGroupTarget.model_group_protocol"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ModelGroupTarget.channel"`)}
	}
	return nil
}

func (_c *ModelGroupTargetCreate) sqlSave(ctx context.Context) (*ModelGroupTarget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelGroupTargetCreate) createSpec() (*ModelGroupTarget, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelGroupTarget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelgrouptarget.Table, sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(modelgrouptarget.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.TargetModelID(); ok {
		_spec.SetField(modelgrouptarget.FieldTargetModelID, field.TypeString, value)
		_node.TargetModelID = value
	}
	if value, ok := _c.mutation.OutboundAPIFormat(); ok {
		_spec.SetField(modelgrouptarget.FieldOutboundAPIFormat, field.TypeString, value)
		_node.OutboundAPIFormat = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(modelgrouptarget.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(modelgrouptarget.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(modelgrouptarget.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(modelgrouptarget.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if nodes := _c.mutation.ModelGroupProtocolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelgrouptarget.ModelGroupProtocolTable,
			Columns: []string{modelgrouptarget.ModelGroupProtocolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelGroupProtocolID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelgrouptarget.ChannelTable,
			Columns: []string{modelgrouptarget.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelGroupTarget.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelGroupTargetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelGroupTargetCreate) OnConflict(opts ...sql.ConflictOption) *ModelGroupTargetUpsertOne {
	_c.conflict = opts
	return &ModelGroupTargetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelGroupTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelGroupTargetCreate) OnConflictColumns(columns ...string) *ModelGroupTargetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelGroupTargetUpsertOne{
		create: _c,
	}
}

type (
	// ModelGroupTargetUpsertOne is the builder for "upsert"-ing
	//  one ModelGroupTarget node.
	ModelGroupTargetUpsertOne struct {
		create *ModelGroupTargetCreate
	}

	// ModelGroupTargetUpsert is the "OnConflict" setter.
	ModelGroupTargetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupTargetUpsert) SetUpdatedAt(v time.Time) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateUpdatedAt() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupTargetUpsert) SetDeletedAt(v int) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateDeletedAt() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupTargetUpsert) AddDeletedAt(v int) *ModelGroupTargetUpsert {
	u.Add(modelgrouptarget.FieldDeletedAt, v)
	return u
}

// SetTargetModelID sets the "target_model_id" field.
func (u *ModelGroupTargetUpsert) SetTargetModelID(v string) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldTargetModelID, v)
	return u
}

// UpdateTargetModelID sets the "target_model_id" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateTargetModelID() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldTargetModelID)
	return u
}

// SetOutboundAPIFormat sets the "outbound_api_format" field.
func (u *ModelGroupTargetUpsert) SetOutboundAPIFormat(v string) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldOutboundAPIFormat, v)
	return u
}

// UpdateOutboundAPIFormat sets the "outbound_api_format" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateOutboundAPIFormat() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldOutboundAPIFormat)
	return u
}

// SetPriority sets the "priority" field.
func (u *ModelGroupTargetUpsert) SetPriority(v int) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdatePriority() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *ModelGroupTargetUpsert) AddPriority(v int) *ModelGroupTargetUpsert {
	u.Add(modelgrouptarget.FieldPriority, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ModelGroupTargetUpsert) SetEnabled(v bool) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateEnabled() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldEnabled)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *ModelGroupTargetUpsert) SetCapabilities(v objects.AdapterTargetCapabilities) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateCapabilities() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldCapabilities)
	return u
}

// SetRemark sets the "remark" field.
func (u *ModelGroupTargetUpsert) SetRemark(v string) *ModelGroupTargetUpsert {
	u.Set(modelgrouptarget.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupTargetUpsert) UpdateRemark() *ModelGroupTargetUpsert {
	u.SetExcluded(modelgrouptarget.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupTargetUpsert) ClearRemark() *ModelGroupTargetUpsert {
	u.SetNull(modelgrouptarget.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelGroupTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelGroupTargetUpsertOne) UpdateNewValues() *ModelGroupTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelgrouptarget.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ModelGroupProtocolID(); exists {
			s.SetIgnore(modelgrouptarget.FieldModelGroupProtocolID)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(modelgrouptarget.FieldChannelID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelGroupTarget.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelGroupTargetUpsertOne) Ignore() *ModelGroupTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelGroupTargetUpsertOne) DoNothing() *ModelGroupTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelGroupTargetCreate.OnConflict
// documentation for more info.
func (u *ModelGroupTargetUpsertOne) Update(set func(*ModelGroupTargetUpsert)) *ModelGroupTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelGroupTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupTargetUpsertOne) SetUpdatedAt(v time.Time) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateUpdatedAt() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupTargetUpsertOne) SetDeletedAt(v int) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupTargetUpsertOne) AddDeletedAt(v int) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateDeletedAt() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetTargetModelID sets the "target_model_id" field.
func (u *ModelGroupTargetUpsertOne) SetTargetModelID(v string) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetTargetModelID(v)
	})
}

// UpdateTargetModelID sets the "target_model_id" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateTargetModelID() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateTargetModelID()
	})
}

// SetOutboundAPIFormat sets the "outbound_api_format" field.
func (u *ModelGroupTargetUpsertOne) SetOutboundAPIFormat(v string) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetOutboundAPIFormat(v)
	})
}

// UpdateOutboundAPIFormat sets the "outbound_api_format" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateOutboundAPIFormat() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateOutboundAPIFormat()
	})
}

// SetPriority sets the "priority" field.
func (u *ModelGroupTargetUpsertOne) SetPriority(v int) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ModelGroupTargetUpsertOne) AddPriority(v int) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdatePriority() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ModelGroupTargetUpsertOne) SetEnabled(v bool) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateEnabled() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateEnabled()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *ModelGroupTargetUpsertOne) SetCapabilities(v objects.AdapterTargetCapabilities) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateCapabilities() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateCapabilities()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelGroupTargetUpsertOne) SetRemark(v string) *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertOne) UpdateRemark() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupTargetUpsertOne) ClearRemark() *ModelGroupTargetUpsertOne {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelGroupTargetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelGroupTargetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelGroupTargetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelGroupTargetUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelGroupTargetUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelGroupTargetCreateBulk is the builder for creating many ModelGroupTarget entities in bulk.
type ModelGroupTargetCreateBulk struct {
	config
	err      error
	builders []*ModelGroupTargetCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelGroupTarget entities in the database.
func (_c *ModelGroupTargetCreateBulk) Save(ctx context.Context) ([]*ModelGroupTarget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelGroupTarget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelGroupTargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelGroupTargetCreateBulk) SaveX(ctx context.Context) []*ModelGroupTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelGroupTargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelGroupTargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelGroupTarget.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelGroupTargetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelGroupTargetCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelGroupTargetUpsertBulk {
	_c.conflict = opts
	return &ModelGroupTargetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelGroupTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelGroupTargetCreateBulk) OnConflictColumns(columns ...string) *ModelGroupTargetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelGroupTargetUpsertBulk{
		create: _c,
	}
}

// ModelGroupTargetUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelGroupTarget nodes.
type ModelGroupTargetUpsertBulk struct {
	create *ModelGroupTargetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelGroupTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelGroupTargetUpsertBulk) UpdateNewValues() *ModelGroupTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelgrouptarget.FieldCreatedAt)
			}
			if _, exists := b.mutation.ModelGroupProtocolID(); exists {
				s.SetIgnore(modelgrouptarget.FieldModelGroupProtocolID)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(modelgrouptarget.FieldChannelID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelGroupTarget.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelGroupTargetUpsertBulk) Ignore() *ModelGroupTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelGroupTargetUpsertBulk) DoNothing() *ModelGroupTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelGroupTargetCreateBulk.OnConflict
// documentation for more info.
func (u *ModelGroupTargetUpsertBulk) Update(set func(*ModelGroupTargetUpsert)) *ModelGroupTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelGroupTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelGroupTargetUpsertBulk) SetUpdatedAt(v time.Time) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateUpdatedAt() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ModelGroupTargetUpsertBulk) SetDeletedAt(v int) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ModelGroupTargetUpsertBulk) AddDeletedAt(v int) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateDeletedAt() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetTargetModelID sets the "target_model_id" field.
func (u *ModelGroupTargetUpsertBulk) SetTargetModelID(v string) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetTargetModelID(v)
	})
}

// UpdateTargetModelID sets the "target_model_id" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateTargetModelID() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateTargetModelID()
	})
}

// SetOutboundAPIFormat sets the "outbound_api_format" field.
func (u *ModelGroupTargetUpsertBulk) SetOutboundAPIFormat(v string) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetOutboundAPIFormat(v)
	})
}

// UpdateOutboundAPIFormat sets the "outbound_api_format" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateOutboundAPIFormat() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateOutboundAPIFormat()
	})
}

// SetPriority sets the "priority" field.
func (u *ModelGroupTargetUpsertBulk) SetPriority(v int) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *ModelGroupTargetUpsertBulk) AddPriority(v int) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdatePriority() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ModelGroupTargetUpsertBulk) SetEnabled(v bool) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateEnabled() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateEnabled()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *ModelGroupTargetUpsertBulk) SetCapabilities(v objects.AdapterTargetCapabilities) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateCapabilities() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateCapabilities()
	})
}

// SetRemark sets the "remark" field.
func (u *ModelGroupTargetUpsertBulk) SetRemark(v string) *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ModelGroupTargetUpsertBulk) UpdateRemark() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ModelGroupTargetUpsertBulk) ClearRemark() *ModelGroupTargetUpsertBulk {
	return u.Update(func(s *ModelGroupTargetUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *ModelGroupTargetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelGroupTargetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelGroupTargetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelGroupTargetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
