// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/modelgroup"
	"github.com/looplj/axonhub/internal/ent/modelgroupprotocol"
	"github.com/looplj/axonhub/internal/ent/modelgrouptarget"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ModelGroupProtocolQuery is the builder for querying ModelGroupProtocol entities.
type ModelGroupProtocolQuery struct {
	config
	ctx              *QueryContext
	order            []modelgroupprotocol.OrderOption
	inters           []Interceptor
	predicates       []predicate.ModelGroupProtocol
	withModelGroup   *ModelGroupQuery
	withTargets      *ModelGroupTargetQuery
	loadTotal        []func(context.Context, []*ModelGroupProtocol) error
	modifiers        []func(*sql.Selector)
	withNamedTargets map[string]*ModelGroupTargetQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModelGroupProtocolQuery builder.
func (_q *ModelGroupProtocolQuery) Where(ps ...predicate.ModelGroupProtocol) *ModelGroupProtocolQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ModelGroupProtocolQuery) Limit(limit int) *ModelGroupProtocolQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ModelGroupProtocolQuery) Offset(offset int) *ModelGroupProtocolQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ModelGroupProtocolQuery) Unique(unique bool) *ModelGroupProtocolQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ModelGroupProtocolQuery) Order(o ...modelgroupprotocol.OrderOption) *ModelGroupProtocolQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryModelGroup chains the current query on the "model_group" edge.
func (_q *ModelGroupProtocolQuery) QueryModelGroup() *ModelGroupQuery {
	query := (&ModelGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modelgroupprotocol.Table, modelgroupprotocol.FieldID, selector),
			sqlgraph.To(modelgroup.Table, modelgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelgroupprotocol.ModelGroupTable, modelgroupprotocol.ModelGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTargets chains the current query on the "targets" edge.
func (_q *ModelGroupProtocolQuery) QueryTargets() *ModelGroupTargetQuery {
	query := (&ModelGroupTargetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modelgroupprotocol.Table, modelgroupprotocol.FieldID, selector),
			sqlgraph.To(modelgrouptarget.Table, modelgrouptarget.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, modelgroupprotocol.TargetsTable, modelgroupprotocol.TargetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ModelGroupProtocol entity from the query.
// Returns a *NotFoundError when no ModelGroupProtocol was found.
func (_q *ModelGroupProtocolQuery) First(ctx context.Context) (*ModelGroupProtocol, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{modelgroupprotocol.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) FirstX(ctx context.Context) *ModelGroupProtocol {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModelGroupProtocol ID from the query.
// Returns a *NotFoundError when no ModelGroupProtocol ID was found.
func (_q *ModelGroupProtocolQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{modelgroupprotocol.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModelGroupProtocol entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ModelGroupProtocol entity is found.
// Returns a *NotFoundError when no ModelGroupProtocol entities are found.
func (_q *ModelGroupProtocolQuery) Only(ctx context.Context) (*ModelGroupProtocol, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{modelgroupprotocol.Label}
	default:
		return nil, &NotSingularError{modelgroupprotocol.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) OnlyX(ctx context.Context) *ModelGroupProtocol {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModelGroupProtocol ID in the query.
// Returns a *NotSingularError when more than one ModelGroupProtocol ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ModelGroupProtocolQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{modelgroupprotocol.Label}
	default:
		err = &NotSingularError{modelgroupprotocol.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModelGroupProtocols.
func (_q *ModelGroupProtocolQuery) All(ctx context.Context) ([]*ModelGroupProtocol, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ModelGroupProtocol, *ModelGroupProtocolQuery]()
	return withInterceptors[[]*ModelGroupProtocol](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) AllX(ctx context.Context) []*ModelGroupProtocol {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModelGroupProtocol IDs.
func (_q *ModelGroupProtocolQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(modelgroupprotocol.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ModelGroupProtocolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ModelGroupProtocolQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ModelGroupProtocolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ModelGroupProtocolQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModelGroupProtocolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ModelGroupProtocolQuery) Clone() *ModelGroupProtocolQuery {
	if _q == nil {
		return nil
	}
	return &ModelGroupProtocolQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]modelgroupprotocol.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.ModelGroupProtocol{}, _q.predicates...),
		withModelGroup: _q.withModelGroup.Clone(),
		withTargets:    _q.withTargets.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithModelGroup tells the query-builder to eager-load the nodes that are connected to
// the "model_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ModelGroupProtocolQuery) WithModelGroup(opts ...func(*ModelGroupQuery)) *ModelGroupProtocolQuery {
	query := (&ModelGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModelGroup = query
	return _q
}

// WithTargets tells the query-builder to eager-load the nodes that are connected to
// the "targets" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ModelGroupProtocolQuery) WithTargets(opts ...func(*ModelGroupTargetQuery)) *ModelGroupProtocolQuery {
	query := (&ModelGroupTargetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTargets = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModelGroupProtocol.Query().
//		GroupBy(modelgroupprotocol.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ModelGroupProtocolQuery) GroupBy(field string, fields ...string) *ModelGroupProtocolGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModelGroupProtocolGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = modelgroupprotocol.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ModelGroupProtocol.Query().
//		Select(modelgroupprotocol.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ModelGroupProtocolQuery) Select(fields ...string) *ModelGroupProtocolSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ModelGroupProtocolSelect{ModelGroupProtocolQuery: _q}
	sbuild.label = modelgroupprotocol.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModelGroupProtocolSelect configured with the given aggregations.
func (_q *ModelGroupProtocolQuery) Aggregate(fns ...AggregateFunc) *ModelGroupProtocolSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ModelGroupProtocolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !modelgroupprotocol.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ModelGroupProtocolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ModelGroupProtocol, error) {
	var (
		nodes       = []*ModelGroupProtocol{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withModelGroup != nil,
			_q.withTargets != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ModelGroupProtocol).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ModelGroupProtocol{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withModelGroup; query != nil {
		if err := _q.loadModelGroup(ctx, query, nodes, nil,
			func(n *ModelGroupProtocol, e *ModelGroup) { n.Edges.ModelGroup = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTargets; query != nil {
		if err := _q.loadTargets(ctx, query, nodes,
			func(n *ModelGroupProtocol) { n.Edges.Targets = []*ModelGroupTarget{} },
			func(n *ModelGroupProtocol, e *ModelGroupTarget) { n.Edges.Targets = append(n.Edges.Targets, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedTargets {
		if err := _q.loadTargets(ctx, query, nodes,
			func(n *ModelGroupProtocol) { n.appendNamedTargets(name) },
			func(n *ModelGroupProtocol, e *ModelGroupTarget) { n.appendNamedTargets(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ModelGroupProtocolQuery) loadModelGroup(ctx context.Context, query *ModelGroupQuery, nodes []*ModelGroupProtocol, init func(*ModelGroupProtocol), assign func(*ModelGroupProtocol, *ModelGroup)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ModelGroupProtocol)
	for i := range nodes {
		fk := nodes[i].ModelGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(modelgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ModelGroupProtocolQuery) loadTargets(ctx context.Context, query *ModelGroupTargetQuery, nodes []*ModelGroupProtocol, init func(*ModelGroupProtocol), assign func(*ModelGroupProtocol, *ModelGroupTarget)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ModelGroupProtocol)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(modelgrouptarget.FieldModelGroupProtocolID)
	}
	query.Where(predicate.ModelGroupTarget(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(modelgroupprotocol.TargetsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ModelGroupProtocolID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "model_group_protocol_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ModelGroupProtocolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ModelGroupProtocolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(modelgroupprotocol.Table, modelgroupprotocol.Columns, sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelgroupprotocol.FieldID)
		for i := range fields {
			if fields[i] != modelgroupprotocol.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withModelGroup != nil {
			_spec.Node.AddColumnOnce(modelgroupprotocol.FieldModelGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ModelGroupProtocolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(modelgroupprotocol.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = modelgroupprotocol.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ModelGroupProtocolQuery) Modify(modifiers ...func(s *sql.Selector)) *ModelGroupProtocolSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedTargets tells the query-builder to eager-load the nodes that are connected to the "targets"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *ModelGroupProtocolQuery) WithNamedTargets(name string, opts ...func(*ModelGroupTargetQuery)) *ModelGroupProtocolQuery {
	query := (&ModelGroupTargetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedTargets == nil {
		_q.withNamedTargets = make(map[string]*ModelGroupTargetQuery)
	}
	_q.withNamedTargets[name] = query
	return _q
}

// ModelGroupProtocolGroupBy is the group-by builder for ModelGroupProtocol entities.
type ModelGroupProtocolGroupBy struct {
	selector
	build *ModelGroupProtocolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ModelGroupProtocolGroupBy) Aggregate(fns ...AggregateFunc) *ModelGroupProtocolGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ModelGroupProtocolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelGroupProtocolQuery, *ModelGroupProtocolGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ModelGroupProtocolGroupBy) sqlScan(ctx context.Context, root *ModelGroupProtocolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModelGroupProtocolSelect is the builder for selecting fields of ModelGroupProtocol entities.
type ModelGroupProtocolSelect struct {
	*ModelGroupProtocolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ModelGroupProtocolSelect) Aggregate(fns ...AggregateFunc) *ModelGroupProtocolSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ModelGroupProtocolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelGroupProtocolQuery, *ModelGroupProtocolSelect](ctx, _s.ModelGroupProtocolQuery, _s, _s.inters, v)
}

func (_s *ModelGroupProtocolSelect) sqlScan(ctx context.Context, root *ModelGroupProtocolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ModelGroupProtocolSelect) Modify(modifiers ...func(s *sql.Selector)) *ModelGroupProtocolSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
