// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/modelgroup"
	"github.com/looplj/axonhub/internal/ent/modelgroupprotocol"
)

// ModelGroupProtocol is the model entity for the ModelGroupProtocol schema.
type ModelGroupProtocol struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// ModelGroupID holds the value of the "model_group_id" field.
	ModelGroupID int `json:"model_group_id,omitempty"`
	// InboundAPIFormat holds the value of the "inbound_api_format" field.
	InboundAPIFormat string `json:"inbound_api_format,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelGroupProtocolQuery when eager-loading is set.
	Edges        ModelGroupProtocolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelGroupProtocolEdges holds the relations/edges for other nodes in the graph.
type ModelGroupProtocolEdges struct {
	// ModelGroup holds the value of the model_group edge.
	ModelGroup *ModelGroup `json:"model_group,omitempty"`
	// Targets holds the value of the targets edge.
	Targets []*ModelGroupTarget `json:"targets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool

	namedTargets map[string][]*ModelGroupTarget
}

// ModelGroupOrErr returns the ModelGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelGroupProtocolEdges) ModelGroupOrErr() (*ModelGroup, error) {
	if e.ModelGroup != nil {
		return e.ModelGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: modelgroup.Label}
	}
	return nil, &NotLoadedError{edge: "model_group"}
}

// TargetsOrErr returns the Targets value or an error if the edge
// was not loaded in eager-loading.
func (e ModelGroupProtocolEdges) TargetsOrErr() ([]*ModelGroupTarget, error) {
	if e.loadedTypes[1] {
		return e.Targets, nil
	}
	return nil, &NotLoadedError{edge: "targets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelGroupProtocol) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelgroupprotocol.FieldEnabled:
			values[i] = new(sql.NullBool)
		case modelgroupprotocol.FieldID, modelgroupprotocol.FieldDeletedAt, modelgroupprotocol.FieldModelGroupID:
			values[i] = new(sql.NullInt64)
		case modelgroupprotocol.FieldInboundAPIFormat, modelgroupprotocol.FieldRemark:
			values[i] = new(sql.NullString)
		case modelgroupprotocol.FieldCreatedAt, modelgroupprotocol.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelGroupProtocol fields.
func (_m *ModelGroupProtocol) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelgroupprotocol.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case modelgroupprotocol.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelgroupprotocol.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelgroupprotocol.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case modelgroupprotocol.FieldModelGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_group_id", values[i])
			} else if value.Valid {
				_m.ModelGroupID = int(value.Int64)
			}
		case modelgroupprotocol.FieldInboundAPIFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inbound_api_format", values[i])
			} else if value.Valid {
				_m.InboundAPIFormat = value.String
			}
		case modelgroupprotocol.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case modelgroupprotocol.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelGroupProtocol.
// This includes values selected through modifiers, order, etc.
func (_m *ModelGroupProtocol) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModelGroup queries the "model_group" edge of the ModelGroupProtocol entity.
func (_m *ModelGroupProtocol) QueryModelGroup() *ModelGroupQuery {
	return NewModelGroupProtocolClient(_m.config).QueryModelGroup(_m)
}

// QueryTargets queries the "targets" edge of the ModelGroupProtocol entity.
func (_m *ModelGroupProtocol) QueryTargets() *ModelGroupTargetQuery {
	return NewModelGroupProtocolClient(_m.config).QueryTargets(_m)
}

// Update returns a builder for updating this ModelGroupProtocol.
// Note that you need to call ModelGroupProtocol.Unwrap() before calling this method if this ModelGroupProtocol
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelGroupProtocol) Update() *ModelGroupProtocolUpdateOne {
	return NewModelGroupProtocolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelGroupProtocol entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelGroupProtocol) Unwrap() *ModelGroupProtocol {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelGroupProtocol is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelGroupProtocol) String() string {
	var builder strings.Builder
	builder.WriteString("ModelGroupProtocol(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("model_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelGroupID))
	builder.WriteString(", ")
	builder.WriteString("inbound_api_format=")
	builder.WriteString(_m.InboundAPIFormat)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedTargets returns the Targets named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *ModelGroupProtocol) NamedTargets(name string) ([]*ModelGroupTarget, error) {
	if _m.Edges.namedTargets == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTargets[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *ModelGroupProtocol) appendNamedTargets(name string, edges ...*ModelGroupTarget) {
	if _m.Edges.namedTargets == nil {
		_m.Edges.namedTargets = make(map[string][]*ModelGroupTarget)
	}
	if len(edges) == 0 {
		_m.Edges.namedTargets[name] = []*ModelGroupTarget{}
	} else {
		_m.Edges.namedTargets[name] = append(_m.Edges.namedTargets[name], edges...)
	}
}

// ModelGroupProtocols is a parsable slice of ModelGroupProtocol.
type ModelGroupProtocols []*ModelGroupProtocol
