// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroupprotocol"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// ModelGroupProtocolDelete is the builder for deleting a ModelGroupProtocol entity.
type ModelGroupProtocolDelete struct {
	config
	hooks    []Hook
	mutation *ModelGroupProtocolMutation
}

// Where appends a list predicates to the ModelGroupProtocolDelete builder.
func (_d *ModelGroupProtocolDelete) Where(ps ...predicate.ModelGroupProtocol) *ModelGroupProtocolDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelGroupProtocolDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelGroupProtocolDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelGroupProtocolDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelgroupprotocol.Table, sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelGroupProtocolDeleteOne is the builder for deleting a single ModelGroupProtocol entity.
type ModelGroupProtocolDeleteOne struct {
	_d *ModelGroupProtocolDelete
}

// Where appends a list predicates to the ModelGroupProtocolDelete builder.
func (_d *ModelGroupProtocolDeleteOne) Where(ps ...predicate.ModelGroupProtocol) *ModelGroupProtocolDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelGroupProtocolDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelgroupprotocol.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelGroupProtocolDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
