// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroupprotocol"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgrouptarget"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// ModelGroupProtocolUpdate is the builder for updating ModelGroupProtocol entities.
type ModelGroupProtocolUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelGroupProtocolMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelGroupProtocolUpdate builder.
func (_u *ModelGroupProtocolUpdate) Where(ps ...predicate.ModelGroupProtocol) *ModelGroupProtocolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelGroupProtocolUpdate) SetUpdatedAt(v time.Time) *ModelGroupProtocolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelGroupProtocolUpdate) SetDeletedAt(v int) *ModelGroupProtocolUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdate) SetNillableDeletedAt(v *int) *ModelGroupProtocolUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ModelGroupProtocolUpdate) AddDeletedAt(v int) *ModelGroupProtocolUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (_u *ModelGroupProtocolUpdate) SetInboundAPIFormat(v string) *ModelGroupProtocolUpdate {
	_u.mutation.SetInboundAPIFormat(v)
	return _u
}

// SetNillableInboundAPIFormat sets the "inbound_api_format" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdate) SetNillableInboundAPIFormat(v *string) *ModelGroupProtocolUpdate {
	if v != nil {
		_u.SetInboundAPIFormat(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelGroupProtocolUpdate) SetEnabled(v bool) *ModelGroupProtocolUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdate) SetNillableEnabled(v *bool) *ModelGroupProtocolUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelGroupProtocolUpdate) SetRemark(v string) *ModelGroupProtocolUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdate) SetNillableRemark(v *string) *ModelGroupProtocolUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelGroupProtocolUpdate) ClearRemark() *ModelGroupProtocolUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// AddTargetIDs adds the "targets" edge to the ModelGroupTarget entity by IDs.
func (_u *ModelGroupProtocolUpdate) AddTargetIDs(ids ...int) *ModelGroupProtocolUpdate {
	_u.mutation.AddTargetIDs(ids...)
	return _u
}

// AddTargets adds the "targets" edges to the ModelGroupTarget entity.
func (_u *ModelGroupProtocolUpdate) AddTargets(v ...*ModelGroupTarget) *ModelGroupProtocolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTargetIDs(ids...)
}

// Mutation returns the ModelGroupProtocolMutation object of the builder.
func (_u *ModelGroupProtocolUpdate) Mutation() *ModelGroupProtocolMutation {
	return _u.mutation
}

// ClearTargets clears all "targets" edges to the ModelGroupTarget entity.
func (_u *ModelGroupProtocolUpdate) ClearTargets() *ModelGroupProtocolUpdate {
	_u.mutation.ClearTargets()
	return _u
}

// RemoveTargetIDs removes the "targets" edge to ModelGroupTarget entities by IDs.
func (_u *ModelGroupProtocolUpdate) RemoveTargetIDs(ids ...int) *ModelGroupProtocolUpdate {
	_u.mutation.RemoveTargetIDs(ids...)
	return _u
}

// RemoveTargets removes "targets" edges to ModelGroupTarget entities.
func (_u *ModelGroupProtocolUpdate) RemoveTargets(v ...*ModelGroupTarget) *ModelGroupProtocolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTargetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelGroupProtocolUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelGroupProtocolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelGroupProtocolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelGroupProtocolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelGroupProtocolUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelgroupprotocol.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroupprotocol.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroupprotocol.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelGroupProtocolUpdate) check() error {
	if _u.mutation.ModelGroupCleared() && len(_u.mutation.ModelGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelGroupProtocol.model_group"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelGroupProtocolUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelGroupProtocolUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelGroupProtocolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelgroupprotocol.Table, modelgroupprotocol.Columns, sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(modelgroupprotocol.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InboundAPIFormat(); ok {
		_spec.SetField(modelgroupprotocol.FieldInboundAPIFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelgroupprotocol.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(modelgroupprotocol.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(modelgroupprotocol.FieldRemark, field.TypeString)
	}
	if _u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTargetsIDs(); len(nodes) > 0 && !_u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelgroupprotocol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelGroupProtocolUpdateOne is the builder for updating a single ModelGroupProtocol entity.
type ModelGroupProtocolUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelGroupProtocolMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelGroupProtocolUpdateOne) SetUpdatedAt(v time.Time) *ModelGroupProtocolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelGroupProtocolUpdateOne) SetDeletedAt(v int) *ModelGroupProtocolUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdateOne) SetNillableDeletedAt(v *int) *ModelGroupProtocolUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ModelGroupProtocolUpdateOne) AddDeletedAt(v int) *ModelGroupProtocolUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetInboundAPIFormat sets the "inbound_api_format" field.
func (_u *ModelGroupProtocolUpdateOne) SetInboundAPIFormat(v string) *ModelGroupProtocolUpdateOne {
	_u.mutation.SetInboundAPIFormat(v)
	return _u
}

// SetNillableInboundAPIFormat sets the "inbound_api_format" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdateOne) SetNillableInboundAPIFormat(v *string) *ModelGroupProtocolUpdateOne {
	if v != nil {
		_u.SetInboundAPIFormat(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelGroupProtocolUpdateOne) SetEnabled(v bool) *ModelGroupProtocolUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdateOne) SetNillableEnabled(v *bool) *ModelGroupProtocolUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelGroupProtocolUpdateOne) SetRemark(v string) *ModelGroupProtocolUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelGroupProtocolUpdateOne) SetNillableRemark(v *string) *ModelGroupProtocolUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelGroupProtocolUpdateOne) ClearRemark() *ModelGroupProtocolUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// AddTargetIDs adds the "targets" edge to the ModelGroupTarget entity by IDs.
func (_u *ModelGroupProtocolUpdateOne) AddTargetIDs(ids ...int) *ModelGroupProtocolUpdateOne {
	_u.mutation.AddTargetIDs(ids...)
	return _u
}

// AddTargets adds the "targets" edges to the ModelGroupTarget entity.
func (_u *ModelGroupProtocolUpdateOne) AddTargets(v ...*ModelGroupTarget) *ModelGroupProtocolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTargetIDs(ids...)
}

// Mutation returns the ModelGroupProtocolMutation object of the builder.
func (_u *ModelGroupProtocolUpdateOne) Mutation() *ModelGroupProtocolMutation {
	return _u.mutation
}

// ClearTargets clears all "targets" edges to the ModelGroupTarget entity.
func (_u *ModelGroupProtocolUpdateOne) ClearTargets() *ModelGroupProtocolUpdateOne {
	_u.mutation.ClearTargets()
	return _u
}

// RemoveTargetIDs removes the "targets" edge to ModelGroupTarget entities by IDs.
func (_u *ModelGroupProtocolUpdateOne) RemoveTargetIDs(ids ...int) *ModelGroupProtocolUpdateOne {
	_u.mutation.RemoveTargetIDs(ids...)
	return _u
}

// RemoveTargets removes "targets" edges to ModelGroupTarget entities.
func (_u *ModelGroupProtocolUpdateOne) RemoveTargets(v ...*ModelGroupTarget) *ModelGroupProtocolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTargetIDs(ids...)
}

// Where appends a list predicates to the ModelGroupProtocolUpdate builder.
func (_u *ModelGroupProtocolUpdateOne) Where(ps ...predicate.ModelGroupProtocol) *ModelGroupProtocolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelGroupProtocolUpdateOne) Select(field string, fields ...string) *ModelGroupProtocolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelGroupProtocol entity.
func (_u *ModelGroupProtocolUpdateOne) Save(ctx context.Context) (*ModelGroupProtocol, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelGroupProtocolUpdateOne) SaveX(ctx context.Context) *ModelGroupProtocol {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelGroupProtocolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelGroupProtocolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelGroupProtocolUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelgroupprotocol.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroupprotocol.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroupprotocol.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelGroupProtocolUpdateOne) check() error {
	if _u.mutation.ModelGroupCleared() && len(_u.mutation.ModelGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ModelGroupProtocol.model_group"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelGroupProtocolUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelGroupProtocolUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelGroupProtocolUpdateOne) sqlSave(ctx context.Context) (_node *ModelGroupProtocol, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelgroupprotocol.Table, modelgroupprotocol.Columns, sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelGroupProtocol.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelgroupprotocol.FieldID)
		for _, f := range fields {
			if !modelgroupprotocol.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelgroupprotocol.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelgroupprotocol.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(modelgroupprotocol.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InboundAPIFormat(); ok {
		_spec.SetField(modelgroupprotocol.FieldInboundAPIFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelgroupprotocol.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(modelgroupprotocol.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(modelgroupprotocol.FieldRemark, field.TypeString)
	}
	if _u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTargetsIDs(); len(nodes) > 0 && !_u.mutation.TargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroupprotocol.TargetsTable,
			Columns: []string{modelgroupprotocol.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgrouptarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelGroupProtocol{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelgroupprotocol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
