// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroup"
	"github.com/mutallipp/llm-proxy/internal/ent/modelgroupprotocol"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// ModelGroupUpdate is the builder for updating ModelGroup entities.
type ModelGroupUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelGroupMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelGroupUpdate builder.
func (_u *ModelGroupUpdate) Where(ps ...predicate.ModelGroup) *ModelGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelGroupUpdate) SetUpdatedAt(v time.Time) *ModelGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelGroupUpdate) SetDeletedAt(v int) *ModelGroupUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelGroupUpdate) SetNillableDeletedAt(v *int) *ModelGroupUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ModelGroupUpdate) AddDeletedAt(v int) *ModelGroupUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ModelGroupUpdate) SetName(v string) *ModelGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModelGroupUpdate) SetNillableName(v *string) *ModelGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelGroupUpdate) SetDisplayName(v string) *ModelGroupUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelGroupUpdate) SetNillableDisplayName(v *string) *ModelGroupUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelGroupUpdate) SetStatus(v modelgroup.Status) *ModelGroupUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelGroupUpdate) SetNillableStatus(v *modelgroup.Status) *ModelGroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (_u *ModelGroupUpdate) SetSelectionStrategy(v modelgroup.SelectionStrategy) *ModelGroupUpdate {
	_u.mutation.SetSelectionStrategy(v)
	return _u
}

// SetNillableSelectionStrategy sets the "selection_strategy" field if the given value is not nil.
func (_u *ModelGroupUpdate) SetNillableSelectionStrategy(v *modelgroup.SelectionStrategy) *ModelGroupUpdate {
	if v != nil {
		_u.SetSelectionStrategy(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelGroupUpdate) SetRemark(v string) *ModelGroupUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelGroupUpdate) SetNillableRemark(v *string) *ModelGroupUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelGroupUpdate) ClearRemark() *ModelGroupUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// AddProtocolIDs adds the "protocols" edge to the ModelGroupProtocol entity by IDs.
func (_u *ModelGroupUpdate) AddProtocolIDs(ids ...int) *ModelGroupUpdate {
	_u.mutation.AddProtocolIDs(ids...)
	return _u
}

// AddProtocols adds the "protocols" edges to the ModelGroupProtocol entity.
func (_u *ModelGroupUpdate) AddProtocols(v ...*ModelGroupProtocol) *ModelGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProtocolIDs(ids...)
}

// Mutation returns the ModelGroupMutation object of the builder.
func (_u *ModelGroupUpdate) Mutation() *ModelGroupMutation {
	return _u.mutation
}

// ClearProtocols clears all "protocols" edges to the ModelGroupProtocol entity.
func (_u *ModelGroupUpdate) ClearProtocols() *ModelGroupUpdate {
	_u.mutation.ClearProtocols()
	return _u
}

// RemoveProtocolIDs removes the "protocols" edge to ModelGroupProtocol entities by IDs.
func (_u *ModelGroupUpdate) RemoveProtocolIDs(ids ...int) *ModelGroupUpdate {
	_u.mutation.RemoveProtocolIDs(ids...)
	return _u
}

// RemoveProtocols removes "protocols" edges to ModelGroupProtocol entities.
func (_u *ModelGroupUpdate) RemoveProtocols(v ...*ModelGroupProtocol) *ModelGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProtocolIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelGroupUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelGroupUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelgroup.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroup.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelGroupUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := modelgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelGroup.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SelectionStrategy(); ok {
		if err := modelgroup.SelectionStrategyValidator(v); err != nil {
			return &ValidationError{Name: "selection_strategy", err: fmt.Errorf(`ent: validator failed for field "ModelGroup.selection_strategy": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelGroupUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelGroupUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelgroup.Table, modelgroup.Columns, sqlgraph.NewFieldSpec(modelgroup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelgroup.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(modelgroup.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modelgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelgroup.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelgroup.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SelectionStrategy(); ok {
		_spec.SetField(modelgroup.FieldSelectionStrategy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(modelgroup.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(modelgroup.FieldRemark, field.TypeString)
	}
	if _u.mutation.ProtocolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProtocolsIDs(); len(nodes) > 0 && !_u.mutation.ProtocolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProtocolsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelGroupUpdateOne is the builder for updating a single ModelGroup entity.
type ModelGroupUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelGroupMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelGroupUpdateOne) SetUpdatedAt(v time.Time) *ModelGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelGroupUpdateOne) SetDeletedAt(v int) *ModelGroupUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelGroupUpdateOne) SetNillableDeletedAt(v *int) *ModelGroupUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ModelGroupUpdateOne) AddDeletedAt(v int) *ModelGroupUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ModelGroupUpdateOne) SetName(v string) *ModelGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModelGroupUpdateOne) SetNillableName(v *string) *ModelGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelGroupUpdateOne) SetDisplayName(v string) *ModelGroupUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelGroupUpdateOne) SetNillableDisplayName(v *string) *ModelGroupUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelGroupUpdateOne) SetStatus(v modelgroup.Status) *ModelGroupUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelGroupUpdateOne) SetNillableStatus(v *modelgroup.Status) *ModelGroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (_u *ModelGroupUpdateOne) SetSelectionStrategy(v modelgroup.SelectionStrategy) *ModelGroupUpdateOne {
	_u.mutation.SetSelectionStrategy(v)
	return _u
}

// SetNillableSelectionStrategy sets the "selection_strategy" field if the given value is not nil.
func (_u *ModelGroupUpdateOne) SetNillableSelectionStrategy(v *modelgroup.SelectionStrategy) *ModelGroupUpdateOne {
	if v != nil {
		_u.SetSelectionStrategy(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelGroupUpdateOne) SetRemark(v string) *ModelGroupUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelGroupUpdateOne) SetNillableRemark(v *string) *ModelGroupUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelGroupUpdateOne) ClearRemark() *ModelGroupUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// AddProtocolIDs adds the "protocols" edge to the ModelGroupProtocol entity by IDs.
func (_u *ModelGroupUpdateOne) AddProtocolIDs(ids ...int) *ModelGroupUpdateOne {
	_u.mutation.AddProtocolIDs(ids...)
	return _u
}

// AddProtocols adds the "protocols" edges to the ModelGroupProtocol entity.
func (_u *ModelGroupUpdateOne) AddProtocols(v ...*ModelGroupProtocol) *ModelGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProtocolIDs(ids...)
}

// Mutation returns the ModelGroupMutation object of the builder.
func (_u *ModelGroupUpdateOne) Mutation() *ModelGroupMutation {
	return _u.mutation
}

// ClearProtocols clears all "protocols" edges to the ModelGroupProtocol entity.
func (_u *ModelGroupUpdateOne) ClearProtocols() *ModelGroupUpdateOne {
	_u.mutation.ClearProtocols()
	return _u
}

// RemoveProtocolIDs removes the "protocols" edge to ModelGroupProtocol entities by IDs.
func (_u *ModelGroupUpdateOne) RemoveProtocolIDs(ids ...int) *ModelGroupUpdateOne {
	_u.mutation.RemoveProtocolIDs(ids...)
	return _u
}

// RemoveProtocols removes "protocols" edges to ModelGroupProtocol entities.
func (_u *ModelGroupUpdateOne) RemoveProtocols(v ...*ModelGroupProtocol) *ModelGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProtocolIDs(ids...)
}

// Where appends a list predicates to the ModelGroupUpdate builder.
func (_u *ModelGroupUpdateOne) Where(ps ...predicate.ModelGroup) *ModelGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelGroupUpdateOne) Select(field string, fields ...string) *ModelGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelGroup entity.
func (_u *ModelGroupUpdateOne) Save(ctx context.Context) (*ModelGroup, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelGroupUpdateOne) SaveX(ctx context.Context) *ModelGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelGroupUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelgroup.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelgroup.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := modelgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelGroup.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SelectionStrategy(); ok {
		if err := modelgroup.SelectionStrategyValidator(v); err != nil {
			return &ValidationError{Name: "selection_strategy", err: fmt.Errorf(`ent: validator failed for field "ModelGroup.selection_strategy": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelGroupUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelGroupUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelGroupUpdateOne) sqlSave(ctx context.Context) (_node *ModelGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelgroup.Table, modelgroup.Columns, sqlgraph.NewFieldSpec(modelgroup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelgroup.FieldID)
		for _, f := range fields {
			if !modelgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelgroup.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(modelgroup.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modelgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelgroup.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelgroup.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SelectionStrategy(); ok {
		_spec.SetField(modelgroup.FieldSelectionStrategy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(modelgroup.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(modelgroup.FieldRemark, field.TypeString)
	}
	if _u.mutation.ProtocolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProtocolsIDs(); len(nodes) > 0 && !_u.mutation.ProtocolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProtocolsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelgroup.ProtocolsTable,
			Columns: []string{modelgroup.ProtocolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelgroupprotocol.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
