// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/modelgroupprotocol"
	"github.com/looplj/axonhub/internal/ent/modelgrouptarget"
	"github.com/looplj/axonhub/internal/objects"
)

// ModelGroupTarget is the model entity for the ModelGroupTarget schema.
type ModelGroupTarget struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// ModelGroupProtocolID holds the value of the "model_group_protocol_id" field.
	ModelGroupProtocolID int `json:"model_group_protocol_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// TargetModelID holds the value of the "target_model_id" field.
	TargetModelID string `json:"target_model_id,omitempty"`
	// OutboundAPIFormat holds the value of the "outbound_api_format" field.
	OutboundAPIFormat string `json:"outbound_api_format,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities objects.AdapterTargetCapabilities `json:"capabilities,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelGroupTargetQuery when eager-loading is set.
	Edges        ModelGroupTargetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelGroupTargetEdges holds the relations/edges for other nodes in the graph.
type ModelGroupTargetEdges struct {
	// ModelGroupProtocol holds the value of the model_group_protocol edge.
	ModelGroupProtocol *ModelGroupProtocol `json:"model_group_protocol,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ModelGroupProtocolOrErr returns the ModelGroupProtocol value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelGroupTargetEdges) ModelGroupProtocolOrErr() (*ModelGroupProtocol, error) {
	if e.ModelGroupProtocol != nil {
		return e.ModelGroupProtocol, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: modelgroupprotocol.Label}
	}
	return nil, &NotLoadedError{edge: "model_group_protocol"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelGroupTargetEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelGroupTarget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelgrouptarget.FieldCapabilities:
			values[i] = new([]byte)
		case modelgrouptarget.FieldEnabled:
			values[i] = new(sql.NullBool)
		case modelgrouptarget.FieldID, modelgrouptarget.FieldDeletedAt, modelgrouptarget.FieldModelGroupProtocolID, modelgrouptarget.FieldChannelID, modelgrouptarget.FieldPriority:
			values[i] = new(sql.NullInt64)
		case modelgrouptarget.FieldTargetModelID, modelgrouptarget.FieldOutboundAPIFormat, modelgrouptarget.FieldRemark:
			values[i] = new(sql.NullString)
		case modelgrouptarget.FieldCreatedAt, modelgrouptarget.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelGroupTarget fields.
func (_m *ModelGroupTarget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelgrouptarget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case modelgrouptarget.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelgrouptarget.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelgrouptarget.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case modelgrouptarget.FieldModelGroupProtocolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_group_protocol_id", values[i])
			} else if value.Valid {
				_m.ModelGroupProtocolID = int(value.Int64)
			}
		case modelgrouptarget.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case modelgrouptarget.FieldTargetModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_model_id", values[i])
			} else if value.Valid {
				_m.TargetModelID = value.String
			}
		case modelgrouptarget.FieldOutboundAPIFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_api_format", values[i])
			} else if value.Valid {
				_m.OutboundAPIFormat = value.String
			}
		case modelgrouptarget.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case modelgrouptarget.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case modelgrouptarget.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case modelgrouptarget.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelGroupTarget.
// This includes values selected through modifiers, order, etc.
func (_m *ModelGroupTarget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModelGroupProtocol queries the "model_group_protocol" edge of the ModelGroupTarget entity.
func (_m *ModelGroupTarget) QueryModelGroupProtocol() *ModelGroupProtocolQuery {
	return NewModelGroupTargetClient(_m.config).QueryModelGroupProtocol(_m)
}

// QueryChannel queries the "channel" edge of the ModelGroupTarget entity.
func (_m *ModelGroupTarget) QueryChannel() *ChannelQuery {
	return NewModelGroupTargetClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ModelGroupTarget.
// Note that you need to call ModelGroupTarget.Unwrap() before calling this method if this ModelGroupTarget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelGroupTarget) Update() *ModelGroupTargetUpdateOne {
	return NewModelGroupTargetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelGroupTarget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelGroupTarget) Unwrap() *ModelGroupTarget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelGroupTarget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelGroupTarget) String() string {
	var builder strings.Builder
	builder.WriteString("ModelGroupTarget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("model_group_protocol_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelGroupProtocolID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("target_model_id=")
	builder.WriteString(_m.TargetModelID)
	builder.WriteString(", ")
	builder.WriteString("outbound_api_format=")
	builder.WriteString(_m.OutboundAPIFormat)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelGroupTargets is a parsable slice of ModelGroupTarget.
type ModelGroupTargets []*ModelGroupTarget
