// Code generated by ent, DO NOT EDIT.

package requestexecution

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the requestexecution type in the database.
	Label = "request_execution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldDataStorageID holds the string denoting the data_storage_id field in the database.
	FieldDataStorageID = "data_storage_id"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldRequestBodyAvailability holds the string denoting the request_body_availability field in the database.
	FieldRequestBodyAvailability = "request_body_availability"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldResponseBodyAvailability holds the string denoting the response_body_availability field in the database.
	FieldResponseBodyAvailability = "response_body_availability"
	// FieldResponseChunks holds the string denoting the response_chunks field in the database.
	FieldResponseChunks = "response_chunks"
	// FieldResponseChunksAvailability holds the string denoting the response_chunks_availability field in the database.
	FieldResponseChunksAvailability = "response_chunks_availability"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldResponseStatusCode holds the string denoting the response_status_code field in the database.
	FieldResponseStatusCode = "response_status_code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldMetricsLatencyMs holds the string denoting the metrics_latency_ms field in the database.
	FieldMetricsLatencyMs = "metrics_latency_ms"
	// FieldMetricsFirstTokenLatencyMs holds the string denoting the metrics_first_token_latency_ms field in the database.
	FieldMetricsFirstTokenLatencyMs = "metrics_first_token_latency_ms"
	// FieldMetricsReasoningDurationMs holds the string denoting the metrics_reasoning_duration_ms field in the database.
	FieldMetricsReasoningDurationMs = "metrics_reasoning_duration_ms"
	// FieldRequestHeaders holds the string denoting the request_headers field in the database.
	FieldRequestHeaders = "request_headers"
	// FieldRequestURL holds the string denoting the request_url field in the database.
	FieldRequestURL = "request_url"
	// FieldPassThroughApplied holds the string denoting the pass_through_applied field in the database.
	FieldPassThroughApplied = "pass_through_applied"
	// EdgeRequest holds the string denoting the request edge name in mutations.
	EdgeRequest = "request"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgeDataStorage holds the string denoting the data_storage edge name in mutations.
	EdgeDataStorage = "data_storage"
	// Table holds the table name of the requestexecution in the database.
	Table = "request_executions"
	// RequestTable is the table that holds the request relation/edge.
	RequestTable = "request_executions"
	// RequestInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestInverseTable = "requests"
	// RequestColumn is the table column denoting the request relation/edge.
	RequestColumn = "request_id"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "request_executions"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
	// DataStorageTable is the table that holds the data_storage relation/edge.
	DataStorageTable = "request_executions"
	// DataStorageInverseTable is the table name for the DataStorage entity.
	// It exists in this package in order to avoid circular dependency with the "datastorage" package.
	DataStorageInverseTable = "data_storages"
	// DataStorageColumn is the table column denoting the data_storage relation/edge.
	DataStorageColumn = "data_storage_id"
)

// Columns holds all SQL columns for requestexecution fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProjectID,
	FieldRequestID,
	FieldChannelID,
	FieldDataStorageID,
	FieldExternalID,
	FieldModelID,
	FieldFormat,
	FieldRequestBody,
	FieldRequestBodyAvailability,
	FieldResponseBody,
	FieldResponseBodyAvailability,
	FieldResponseChunks,
	FieldResponseChunksAvailability,
	FieldErrorMessage,
	FieldResponseStatusCode,
	FieldStatus,
	FieldStream,
	FieldMetricsLatencyMs,
	FieldMetricsFirstTokenLatencyMs,
	FieldMetricsReasoningDurationMs,
	FieldRequestHeaders,
	FieldRequestURL,
	FieldPassThroughApplied,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProjectID holds the default value on creation for the "project_id" field.
	DefaultProjectID int
	// ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	ExternalIDValidator func(string) error
	// DefaultFormat holds the default value on creation for the "format" field.
	DefaultFormat string
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultPassThroughApplied holds the default value on creation for the "pass_through_applied" field.
	DefaultPassThroughApplied bool
)

// RequestBodyAvailability defines the type for the "request_body_availability" enum field.
type RequestBodyAvailability string

// RequestBodyAvailabilityUnknown is the default value of the RequestBodyAvailability enum.
const DefaultRequestBodyAvailability = RequestBodyAvailabilityUnknown

// RequestBodyAvailability values.
const (
	RequestBodyAvailabilityUnknown     RequestBodyAvailability = "unknown"
	RequestBodyAvailabilityAvailable   RequestBodyAvailability = "available"
	RequestBodyAvailabilityUnavailable RequestBodyAvailability = "unavailable"
)

func (rba RequestBodyAvailability) String() string {
	return string(rba)
}

// RequestBodyAvailabilityValidator is a validator for the "request_body_availability" field enum values. It is called by the builders before save.
func RequestBodyAvailabilityValidator(rba RequestBodyAvailability) error {
	switch rba {
	case RequestBodyAvailabilityUnknown, RequestBodyAvailabilityAvailable, RequestBodyAvailabilityUnavailable:
		return nil
	default:
		return fmt.Errorf("requestexecution: invalid enum value for request_body_availability field: %q", rba)
	}
}

// ResponseBodyAvailability defines the type for the "response_body_availability" enum field.
type ResponseBodyAvailability string

// ResponseBodyAvailabilityUnknown is the default value of the ResponseBodyAvailability enum.
const DefaultResponseBodyAvailability = ResponseBodyAvailabilityUnknown

// ResponseBodyAvailability values.
const (
	ResponseBodyAvailabilityUnknown     ResponseBodyAvailability = "unknown"
	ResponseBodyAvailabilityAvailable   ResponseBodyAvailability = "available"
	ResponseBodyAvailabilityUnavailable ResponseBodyAvailability = "unavailable"
)

func (rba ResponseBodyAvailability) String() string {
	return string(rba)
}

// ResponseBodyAvailabilityValidator is a validator for the "response_body_availability" field enum values. It is called by the builders before save.
func ResponseBodyAvailabilityValidator(rba ResponseBodyAvailability) error {
	switch rba {
	case ResponseBodyAvailabilityUnknown, ResponseBodyAvailabilityAvailable, ResponseBodyAvailabilityUnavailable:
		return nil
	default:
		return fmt.Errorf("requestexecution: invalid enum value for response_body_availability field: %q", rba)
	}
}

// ResponseChunksAvailability defines the type for the "response_chunks_availability" enum field.
type ResponseChunksAvailability string

// ResponseChunksAvailabilityUnknown is the default value of the ResponseChunksAvailability enum.
const DefaultResponseChunksAvailability = ResponseChunksAvailabilityUnknown

// ResponseChunksAvailability values.
const (
	ResponseChunksAvailabilityUnknown       ResponseChunksAvailability = "unknown"
	ResponseChunksAvailabilityAvailable     ResponseChunksAvailability = "available"
	ResponseChunksAvailabilityUnavailable   ResponseChunksAvailability = "unavailable"
	ResponseChunksAvailabilityNotApplicable ResponseChunksAvailability = "not_applicable"
)

func (rca ResponseChunksAvailability) String() string {
	return string(rca)
}

// ResponseChunksAvailabilityValidator is a validator for the "response_chunks_availability" field enum values. It is called by the builders before save.
func ResponseChunksAvailabilityValidator(rca ResponseChunksAvailability) error {
	switch rca {
	case ResponseChunksAvailabilityUnknown, ResponseChunksAvailabilityAvailable, ResponseChunksAvailabilityUnavailable, ResponseChunksAvailabilityNotApplicable:
		return nil
	default:
		return fmt.Errorf("requestexecution: invalid enum value for response_chunks_availability field: %q", rca)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusPending    Status = "pending"
	StatusProcessing Status = "processing"
	StatusCompleted  Status = "completed"
	StatusFailed     Status = "failed"
	StatusCanceled   Status = "canceled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusProcessing, StatusCompleted, StatusFailed, StatusCanceled:
		return nil
	default:
		return fmt.Errorf("requestexecution: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the RequestExecution queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByDataStorageID orders the results by the data_storage_id field.
func ByDataStorageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataStorageID, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByRequestBodyAvailability orders the results by the request_body_availability field.
func ByRequestBodyAvailability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodyAvailability, opts...).ToFunc()
}

// ByResponseBodyAvailability orders the results by the response_body_availability field.
func ByResponseBodyAvailability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyAvailability, opts...).ToFunc()
}

// ByResponseChunksAvailability orders the results by the response_chunks_availability field.
func ByResponseChunksAvailability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseChunksAvailability, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByResponseStatusCode orders the results by the response_status_code field.
func ByResponseStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseStatusCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByMetricsLatencyMs orders the results by the metrics_latency_ms field.
func ByMetricsLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsLatencyMs, opts...).ToFunc()
}

// ByMetricsFirstTokenLatencyMs orders the results by the metrics_first_token_latency_ms field.
func ByMetricsFirstTokenLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsFirstTokenLatencyMs, opts...).ToFunc()
}

// ByMetricsReasoningDurationMs orders the results by the metrics_reasoning_duration_ms field.
func ByMetricsReasoningDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsReasoningDurationMs, opts...).ToFunc()
}

// ByRequestURL orders the results by the request_url field.
func ByRequestURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestURL, opts...).ToFunc()
}

// ByPassThroughApplied orders the results by the pass_through_applied field.
func ByPassThroughApplied(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassThroughApplied, opts...).ToFunc()
}

// ByRequestField orders the results by request field.
func ByRequestField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByDataStorageField orders the results by data_storage field.
func ByDataStorageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDataStorageStep(), sql.OrderByField(field, opts...))
	}
}
func newRequestStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RequestTable, RequestColumn),
	)
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newDataStorageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DataStorageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DataStorageTable, DataStorageColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e RequestBodyAvailability) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *RequestBodyAvailability) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = RequestBodyAvailability(str)
	if err := RequestBodyAvailabilityValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid RequestBodyAvailability", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ResponseBodyAvailability) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ResponseBodyAvailability) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ResponseBodyAvailability(str)
	if err := ResponseBodyAvailabilityValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ResponseBodyAvailability", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ResponseChunksAvailability) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ResponseChunksAvailability) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ResponseChunksAvailability(str)
	if err := ResponseChunksAvailabilityValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ResponseChunksAvailability", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
