// Code generated by ent, DO NOT EDIT.

package modelgroup

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelgroup type in the database.
	Label = "model_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSelectionStrategy holds the string denoting the selection_strategy field in the database.
	FieldSelectionStrategy = "selection_strategy"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeProtocols holds the string denoting the protocols edge name in mutations.
	EdgeProtocols = "protocols"
	// Table holds the table name of the modelgroup in the database.
	Table = "model_groups"
	// ProtocolsTable is the table that holds the protocols relation/edge.
	ProtocolsTable = "model_group_protocols"
	// ProtocolsInverseTable is the table name for the ModelGroupProtocol entity.
	// It exists in this package in order to avoid circular dependency with the "modelgroupprotocol" package.
	ProtocolsInverseTable = "model_group_protocols"
	// ProtocolsColumn is the table column denoting the protocols relation/edge.
	ProtocolsColumn = "model_group_id"
)

// Columns holds all SQL columns for modelgroup fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDisplayName,
	FieldStatus,
	FieldSelectionStrategy,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/mutallipp/llm-proxy/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultDisplayName holds the default value on creation for the "display_name" field.
	DefaultDisplayName string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusDisabled is the default value of the Status enum.
const DefaultStatus = StatusDisabled

// Status values.
const (
	StatusEnabled  Status = "enabled"
	StatusDisabled Status = "disabled"
	StatusArchived Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusEnabled, StatusDisabled, StatusArchived:
		return nil
	default:
		return fmt.Errorf("modelgroup: invalid enum value for status field: %q", s)
	}
}

// SelectionStrategy defines the type for the "selection_strategy" enum field.
type SelectionStrategy string

// SelectionStrategyPriorityFailover is the default value of the SelectionStrategy enum.
const DefaultSelectionStrategy = SelectionStrategyPriorityFailover

// SelectionStrategy values.
const (
	SelectionStrategyPriorityFailover SelectionStrategy = "priority_failover"
)

func (ss SelectionStrategy) String() string {
	return string(ss)
}

// SelectionStrategyValidator is a validator for the "selection_strategy" field enum values. It is called by the builders before save.
func SelectionStrategyValidator(ss SelectionStrategy) error {
	switch ss {
	case SelectionStrategyPriorityFailover:
		return nil
	default:
		return fmt.Errorf("modelgroup: invalid enum value for selection_strategy field: %q", ss)
	}
}

// OrderOption defines the ordering options for the ModelGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySelectionStrategy orders the results by the selection_strategy field.
func BySelectionStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectionStrategy, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByProtocolsCount orders the results by protocols count.
func ByProtocolsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProtocolsStep(), opts...)
	}
}

// ByProtocols orders the results by protocols terms.
func ByProtocols(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProtocolsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProtocolsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProtocolsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProtocolsTable, ProtocolsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e SelectionStrategy) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *SelectionStrategy) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = SelectionStrategy(str)
	if err := SelectionStrategyValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid SelectionStrategy", str)
	}
	return nil
}
