// Code generated by ent, DO NOT EDIT.

package modelgrouptarget

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/objects"
)

const (
	// Label holds the string label denoting the modelgrouptarget type in the database.
	Label = "model_group_target"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldModelGroupProtocolID holds the string denoting the model_group_protocol_id field in the database.
	FieldModelGroupProtocolID = "model_group_protocol_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldTargetModelID holds the string denoting the target_model_id field in the database.
	FieldTargetModelID = "target_model_id"
	// FieldOutboundAPIFormat holds the string denoting the outbound_api_format field in the database.
	FieldOutboundAPIFormat = "outbound_api_format"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeModelGroupProtocol holds the string denoting the model_group_protocol edge name in mutations.
	EdgeModelGroupProtocol = "model_group_protocol"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the modelgrouptarget in the database.
	Table = "model_group_targets"
	// ModelGroupProtocolTable is the table that holds the model_group_protocol relation/edge.
	ModelGroupProtocolTable = "model_group_targets"
	// ModelGroupProtocolInverseTable is the table name for the ModelGroupProtocol entity.
	// It exists in this package in order to avoid circular dependency with the "modelgroupprotocol" package.
	ModelGroupProtocolInverseTable = "model_group_protocols"
	// ModelGroupProtocolColumn is the table column denoting the model_group_protocol relation/edge.
	ModelGroupProtocolColumn = "model_group_protocol_id"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "model_group_targets"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for modelgrouptarget fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldModelGroupProtocolID,
	FieldChannelID,
	FieldTargetModelID,
	FieldOutboundAPIFormat,
	FieldPriority,
	FieldEnabled,
	FieldCapabilities,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCapabilities holds the default value on creation for the "capabilities" field.
	DefaultCapabilities objects.AdapterTargetCapabilities
)

// OrderOption defines the ordering options for the ModelGroupTarget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByModelGroupProtocolID orders the results by the model_group_protocol_id field.
func ByModelGroupProtocolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelGroupProtocolID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByTargetModelID orders the results by the target_model_id field.
func ByTargetModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetModelID, opts...).ToFunc()
}

// ByOutboundAPIFormat orders the results by the outbound_api_format field.
func ByOutboundAPIFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundAPIFormat, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByModelGroupProtocolField orders the results by model_group_protocol field.
func ByModelGroupProtocolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelGroupProtocolStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newModelGroupProtocolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelGroupProtocolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelGroupProtocolTable, ModelGroupProtocolColumn),
	)
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
