// Code generated by ent, DO NOT EDIT.

package modelgrouptarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldDeletedAt, v))
}

// ModelGroupProtocolID applies equality check predicate on the "model_group_protocol_id" field. It's identical to ModelGroupProtocolIDEQ.
func ModelGroupProtocolID(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldModelGroupProtocolID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldChannelID, v))
}

// TargetModelID applies equality check predicate on the "target_model_id" field. It's identical to TargetModelIDEQ.
func TargetModelID(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldTargetModelID, v))
}

// OutboundAPIFormat applies equality check predicate on the "outbound_api_format" field. It's identical to OutboundAPIFormatEQ.
func OutboundAPIFormat(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldOutboundAPIFormat, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldEnabled, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldDeletedAt, v))
}

// ModelGroupProtocolIDEQ applies the EQ predicate on the "model_group_protocol_id" field.
func ModelGroupProtocolIDEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldModelGroupProtocolID, v))
}

// ModelGroupProtocolIDNEQ applies the NEQ predicate on the "model_group_protocol_id" field.
func ModelGroupProtocolIDNEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldModelGroupProtocolID, v))
}

// ModelGroupProtocolIDIn applies the In predicate on the "model_group_protocol_id" field.
func ModelGroupProtocolIDIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldModelGroupProtocolID, vs...))
}

// ModelGroupProtocolIDNotIn applies the NotIn predicate on the "model_group_protocol_id" field.
func ModelGroupProtocolIDNotIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldModelGroupProtocolID, vs...))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldChannelID, vs...))
}

// TargetModelIDEQ applies the EQ predicate on the "target_model_id" field.
func TargetModelIDEQ(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldTargetModelID, v))
}

// TargetModelIDNEQ applies the NEQ predicate on the "target_model_id" field.
func TargetModelIDNEQ(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldTargetModelID, v))
}

// TargetModelIDIn applies the In predicate on the "target_model_id" field.
func TargetModelIDIn(vs ...string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldTargetModelID, vs...))
}

// TargetModelIDNotIn applies the NotIn predicate on the "target_model_id" field.
func TargetModelIDNotIn(vs ...string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldTargetModelID, vs...))
}

// TargetModelIDGT applies the GT predicate on the "target_model_id" field.
func TargetModelIDGT(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldTargetModelID, v))
}

// TargetModelIDGTE applies the GTE predicate on the "target_model_id" field.
func TargetModelIDGTE(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldTargetModelID, v))
}

// TargetModelIDLT applies the LT predicate on the "target_model_id" field.
func TargetModelIDLT(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldTargetModelID, v))
}

// TargetModelIDLTE applies the LTE predicate on the "target_model_id" field.
func TargetModelIDLTE(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldTargetModelID, v))
}

// TargetModelIDContains applies the Contains predicate on the "target_model_id" field.
func TargetModelIDContains(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldContains(FieldTargetModelID, v))
}

// TargetModelIDHasPrefix applies the HasPrefix predicate on the "target_model_id" field.
func TargetModelIDHasPrefix(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldHasPrefix(FieldTargetModelID, v))
}

// TargetModelIDHasSuffix applies the HasSuffix predicate on the "target_model_id" field.
func TargetModelIDHasSuffix(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldHasSuffix(FieldTargetModelID, v))
}

// TargetModelIDEqualFold applies the EqualFold predicate on the "target_model_id" field.
func TargetModelIDEqualFold(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEqualFold(FieldTargetModelID, v))
}

// TargetModelIDContainsFold applies the ContainsFold predicate on the "target_model_id" field.
func TargetModelIDContainsFold(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldContainsFold(FieldTargetModelID, v))
}

// OutboundAPIFormatEQ applies the EQ predicate on the "outbound_api_format" field.
func OutboundAPIFormatEQ(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatNEQ applies the NEQ predicate on the "outbound_api_format" field.
func OutboundAPIFormatNEQ(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatIn applies the In predicate on the "outbound_api_format" field.
func OutboundAPIFormatIn(vs ...string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldOutboundAPIFormat, vs...))
}

// OutboundAPIFormatNotIn applies the NotIn predicate on the "outbound_api_format" field.
func OutboundAPIFormatNotIn(vs ...string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldOutboundAPIFormat, vs...))
}

// OutboundAPIFormatGT applies the GT predicate on the "outbound_api_format" field.
func OutboundAPIFormatGT(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatGTE applies the GTE predicate on the "outbound_api_format" field.
func OutboundAPIFormatGTE(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatLT applies the LT predicate on the "outbound_api_format" field.
func OutboundAPIFormatLT(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatLTE applies the LTE predicate on the "outbound_api_format" field.
func OutboundAPIFormatLTE(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatContains applies the Contains predicate on the "outbound_api_format" field.
func OutboundAPIFormatContains(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldContains(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatHasPrefix applies the HasPrefix predicate on the "outbound_api_format" field.
func OutboundAPIFormatHasPrefix(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldHasPrefix(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatHasSuffix applies the HasSuffix predicate on the "outbound_api_format" field.
func OutboundAPIFormatHasSuffix(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldHasSuffix(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatEqualFold applies the EqualFold predicate on the "outbound_api_format" field.
func OutboundAPIFormatEqualFold(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEqualFold(FieldOutboundAPIFormat, v))
}

// OutboundAPIFormatContainsFold applies the ContainsFold predicate on the "outbound_api_format" field.
func OutboundAPIFormatContainsFold(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldContainsFold(FieldOutboundAPIFormat, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldEnabled, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.FieldContainsFold(FieldRemark, v))
}

// HasModelGroupProtocol applies the HasEdge predicate on the "model_group_protocol" edge.
func HasModelGroupProtocol() predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ModelGroupProtocolTable, ModelGroupProtocolColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelGroupProtocolWith applies the HasEdge predicate on the "model_group_protocol" edge with a given conditions (other predicates).
func HasModelGroupProtocolWith(preds ...predicate.ModelGroupProtocol) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(func(s *sql.Selector) {
		step := newModelGroupProtocolStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelGroupTarget) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelGroupTarget) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelGroupTarget) predicate.ModelGroupTarget {
	return predicate.ModelGroupTarget(sql.NotPredicates(p))
}
