// Code generated by ent, DO NOT EDIT.

package modelgroupprotocol

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelgroupprotocol type in the database.
	Label = "model_group_protocol"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldModelGroupID holds the string denoting the model_group_id field in the database.
	FieldModelGroupID = "model_group_id"
	// FieldInboundAPIFormat holds the string denoting the inbound_api_format field in the database.
	FieldInboundAPIFormat = "inbound_api_format"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeModelGroup holds the string denoting the model_group edge name in mutations.
	EdgeModelGroup = "model_group"
	// EdgeTargets holds the string denoting the targets edge name in mutations.
	EdgeTargets = "targets"
	// Table holds the table name of the modelgroupprotocol in the database.
	Table = "model_group_protocols"
	// ModelGroupTable is the table that holds the model_group relation/edge.
	ModelGroupTable = "model_group_protocols"
	// ModelGroupInverseTable is the table name for the ModelGroup entity.
	// It exists in this package in order to avoid circular dependency with the "modelgroup" package.
	ModelGroupInverseTable = "model_groups"
	// ModelGroupColumn is the table column denoting the model_group relation/edge.
	ModelGroupColumn = "model_group_id"
	// TargetsTable is the table that holds the targets relation/edge.
	TargetsTable = "model_group_targets"
	// TargetsInverseTable is the table name for the ModelGroupTarget entity.
	// It exists in this package in order to avoid circular dependency with the "modelgrouptarget" package.
	TargetsInverseTable = "model_group_targets"
	// TargetsColumn is the table column denoting the targets relation/edge.
	TargetsColumn = "model_group_protocol_id"
)

// Columns holds all SQL columns for modelgroupprotocol fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldModelGroupID,
	FieldInboundAPIFormat,
	FieldEnabled,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the ModelGroupProtocol queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByModelGroupID orders the results by the model_group_id field.
func ByModelGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelGroupID, opts...).ToFunc()
}

// ByInboundAPIFormat orders the results by the inbound_api_format field.
func ByInboundAPIFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundAPIFormat, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByModelGroupField orders the results by model_group field.
func ByModelGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetsCount orders the results by targets count.
func ByTargetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTargetsStep(), opts...)
	}
}

// ByTargets orders the results by targets terms.
func ByTargets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newModelGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelGroupTable, ModelGroupColumn),
	)
}
func newTargetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TargetsTable, TargetsColumn),
	)
}
