// Code generated by ent, DO NOT EDIT.

package modelgroupprotocol

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mutallipp/llm-proxy/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldDeletedAt, v))
}

// ModelGroupID applies equality check predicate on the "model_group_id" field. It's identical to ModelGroupIDEQ.
func ModelGroupID(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldModelGroupID, v))
}

// InboundAPIFormat applies equality check predicate on the "inbound_api_format" field. It's identical to InboundAPIFormatEQ.
func InboundAPIFormat(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldInboundAPIFormat, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldEnabled, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLTE(FieldDeletedAt, v))
}

// ModelGroupIDEQ applies the EQ predicate on the "model_group_id" field.
func ModelGroupIDEQ(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldModelGroupID, v))
}

// ModelGroupIDNEQ applies the NEQ predicate on the "model_group_id" field.
func ModelGroupIDNEQ(v int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldModelGroupID, v))
}

// ModelGroupIDIn applies the In predicate on the "model_group_id" field.
func ModelGroupIDIn(vs ...int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldModelGroupID, vs...))
}

// ModelGroupIDNotIn applies the NotIn predicate on the "model_group_id" field.
func ModelGroupIDNotIn(vs ...int) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldModelGroupID, vs...))
}

// InboundAPIFormatEQ applies the EQ predicate on the "inbound_api_format" field.
func InboundAPIFormatEQ(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldInboundAPIFormat, v))
}

// InboundAPIFormatNEQ applies the NEQ predicate on the "inbound_api_format" field.
func InboundAPIFormatNEQ(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldInboundAPIFormat, v))
}

// InboundAPIFormatIn applies the In predicate on the "inbound_api_format" field.
func InboundAPIFormatIn(vs ...string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldInboundAPIFormat, vs...))
}

// InboundAPIFormatNotIn applies the NotIn predicate on the "inbound_api_format" field.
func InboundAPIFormatNotIn(vs ...string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldInboundAPIFormat, vs...))
}

// InboundAPIFormatGT applies the GT predicate on the "inbound_api_format" field.
func InboundAPIFormatGT(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGT(FieldInboundAPIFormat, v))
}

// InboundAPIFormatGTE applies the GTE predicate on the "inbound_api_format" field.
func InboundAPIFormatGTE(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGTE(FieldInboundAPIFormat, v))
}

// InboundAPIFormatLT applies the LT predicate on the "inbound_api_format" field.
func InboundAPIFormatLT(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLT(FieldInboundAPIFormat, v))
}

// InboundAPIFormatLTE applies the LTE predicate on the "inbound_api_format" field.
func InboundAPIFormatLTE(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLTE(FieldInboundAPIFormat, v))
}

// InboundAPIFormatContains applies the Contains predicate on the "inbound_api_format" field.
func InboundAPIFormatContains(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldContains(FieldInboundAPIFormat, v))
}

// InboundAPIFormatHasPrefix applies the HasPrefix predicate on the "inbound_api_format" field.
func InboundAPIFormatHasPrefix(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldHasPrefix(FieldInboundAPIFormat, v))
}

// InboundAPIFormatHasSuffix applies the HasSuffix predicate on the "inbound_api_format" field.
func InboundAPIFormatHasSuffix(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldHasSuffix(FieldInboundAPIFormat, v))
}

// InboundAPIFormatEqualFold applies the EqualFold predicate on the "inbound_api_format" field.
func InboundAPIFormatEqualFold(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEqualFold(FieldInboundAPIFormat, v))
}

// InboundAPIFormatContainsFold applies the ContainsFold predicate on the "inbound_api_format" field.
func InboundAPIFormatContainsFold(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldContainsFold(FieldInboundAPIFormat, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldEnabled, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.FieldContainsFold(FieldRemark, v))
}

// HasModelGroup applies the HasEdge predicate on the "model_group" edge.
func HasModelGroup() predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ModelGroupTable, ModelGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelGroupWith applies the HasEdge predicate on the "model_group" edge with a given conditions (other predicates).
func HasModelGroupWith(preds ...predicate.ModelGroup) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(func(s *sql.Selector) {
		step := newModelGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargets applies the HasEdge predicate on the "targets" edge.
func HasTargets() predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TargetsTable, TargetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetsWith applies the HasEdge predicate on the "targets" edge with a given conditions (other predicates).
func HasTargetsWith(preds ...predicate.ModelGroupTarget) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(func(s *sql.Selector) {
		step := newTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelGroupProtocol) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelGroupProtocol) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelGroupProtocol) predicate.ModelGroupProtocol {
	return predicate.ModelGroupProtocol(sql.NotPredicates(p))
}
